### ISSUE TITLE
ServiceLoader osgi problems

### ISSUE THREAD

**Issue by albertogiantin** [ical4j/ical4j#143]
There is a problem with class AbstractCalendarValidatorFactory similar to #125, running code in an osgi system.

> java.lang.ExceptionInInitializerError
	at net.fortuna.ical4j.model.Calendar.<init>(Calendar.java:159)
	at net.fortuna.ical4j.model.Calendar.<init>(Calendar.java:142)
	at net.fortuna.ical4j.data.CalendarBuilder$ContentHandlerImpl.startCalendar(CalendarBuilder.java:307)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:119)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:198)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:178)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:165)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.loadVTimeZone(TimeZoneRegistryImpl.java:237)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.getTimeZone(TimeZoneRegistryImpl.java:205)
	....
Caused by: java.util.NoSuchElementException
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:365)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at net.fortuna.ical4j.validate.AbstractCalendarValidatorFactory.<clinit>(AbstractCalendarValidatorFactory.java:12)
	... 41 more

**Comment by benfortuna** [comment]
I think this is probably more related to #115, however the symptoms are probably a result of the same cause.

For OSGi I do have a PR open #116  but haven't managed to test yet. I'll try to address this shortly.

**Comment by yan-kisen** [comment]
The fix worked for me. Thanks @t-h-e
