### ISSUE TITLE
Exception on TimeZoneRegistry.getTimeZone

### ISSUE THREAD

**Issue by slavag** [ical4j/ical4j#170]
Hi, 
In the version 2.0.2 I started to get this exception, what could be issue here ?

java.util.IllegalFormatConversionException: Y != org.threeten.bp.LocalDateTime
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302)
	at java.util.Formatter$FormatSpecifier.printDateTime(Formatter.java:2835)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2740)
	at java.util.Formatter.format(Formatter.java:2526)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2928)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.addTransitions(TimeZoneRegistryImpl.java:439)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.generateTimezoneForId(TimeZoneRegistryImpl.java:339)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.loadVTimeZone(TimeZoneRegistryImpl.java:253)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.getTimeZone(TimeZoneRegistryImpl.java:212)
	
Thanks

**Comment by benfortuna** [comment]
It seems that some code added to generate timezones isn't working properly. You should be able to workaround this for now by using defined timezone identifiers. Can you provide more details about the timezone used in this test?

**Comment by slavag** [comment]
Hi,
It seems happen to Asia/Rangoon time zone.
Thanks

**Comment by gvauvert** [comment]
Hi,
I notice that 3 previously supported Time Zones are no more supported:
America/Santa_Isabel
Asia/Rangoon
Pacific/Johnston

**Comment by rfc2822** [comment]
I confirm this to be happening for this time zone definition (which seems to be correct):
```
BEGIN:VTIMEZONE
TZID:PST
BEGIN:STANDARD
TZNAME:PST
TZOFFSETTO:-0800
TZOFFSETFROM:-0700
DTSTART:20001105T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
BEGIN:DAYLIGHT
TZNAME:PDT
TZOFFSETTO:-0700
TZOFFSETFROM:-0800
DTSTART:20000312T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
END:VTIMEZONE
```

See also: https://forums.bitfire.at/post/8826

**Comment by benfortuna** [comment]
I was able to reproduce the issue and it looks like the backport of jsr310 may not deal with formats as expected. I'm in process of changing the code and should have a fix shortly.

**Comment by rfc2822** [comment]
Thanks!

**Comment by benfortuna** [comment]
Cool, I'll close the ticket for now.
