### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by slavag** [ical4j/ical4j#172]
Hi,
When I'm calling copy constructor for Calendar, I'm getting this exception:
Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:744)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:742)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:479)
	at net.fortuna.ical4j.model.AbstractContentFactory.getFactory(AbstractContentFactory.java:82)
	at net.fortuna.ical4j.model.PropertyFactoryImpl.createProperty(PropertyFactoryImpl.java:99)
	at net.fortuna.ical4j.model.Property.copy(Property.java:541)
	at net.fortuna.ical4j.model.PropertyList.<init>(PropertyList.java:77)
	at net.fortuna.ical4j.model.Calendar.<init>(Calendar.java:192)

Please advise.
Thanks

**Comment by stellingsimon** [comment]
This issue is a manifestation of issue #154 and has been fixed in ical4j-2.1.0.

**Comment by patzim** [comment]
I seem to hit this again. I think I'm using version 2.2.3 via DAVx5 (version 2.3-gplay (272)).

```
at.bitfire.ical4android.InvalidCalendarException: Couldn't parse iCalendar object
	at at.bitfire.ical4android.Task$Companion.fromReader(Task.kt:69)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager.processVTodo(TasksSyncManager.kt:140)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager.access$processVTodo(TasksSyncManager.kt:44)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager$downloadRemote$2$1$1.invoke(TasksSyncManager.kt:126)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager$downloadRemote$2$1$1.invoke(TasksSyncManager.kt:44)
	at at.bitfire.davdroid.syncadapter.SyncManager.useRemote(SyncManager.kt:820)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager$downloadRemote$2$1.invoke(TasksSyncManager.kt:113)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager$downloadRemote$2$1.invoke(TasksSyncManager.kt:44)
	at at.bitfire.dav4jvm.Response$Companion.parse(Response.kt:211)
	at at.bitfire.dav4jvm.DavResource$processMultiStatus$2.invoke(DavResource.kt:465)
	at at.bitfire.dav4jvm.DavResource.processMultiStatus(DavResource.kt:484)
	at at.bitfire.dav4jvm.DavResource.processMultiStatus(DavResource.kt:435)
	at at.bitfire.dav4jvm.DavCalendar.multiget(DavCalendar.kt:151)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager$downloadRemote$2.invoke(TasksSyncManager.kt:112)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager$downloadRemote$2.invoke(TasksSyncManager.kt:44)
	at at.bitfire.davdroid.syncadapter.SyncManager.useRemote(SyncManager.kt:809)
	at at.bitfire.davdroid.syncadapter.SyncManager.useRemoteCollection(SyncManager.kt:830)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager.downloadRemote(TasksSyncManager.kt:111)
	at at.bitfire.davdroid.syncadapter.SyncManager$syncRemote$1$1.run(SyncManager.kt:451)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: net.fortuna.ical4j.data.ParserException: Error at line 14:null
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:158)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:198)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:178)
	at at.bitfire.ical4android.Task$Companion.fromReader(Task.kt:67)
	... 23 more
Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:429)
	at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:448)
	at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:448)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:447)
	at net.fortuna.ical4j.model.AbstractContentFactory.getFactory(AbstractContentFactory.java:85)
	at net.fortuna.ical4j.model.PropertyFactoryImpl.createProperty(PropertyFactoryImpl.java:70)
	at net.fortuna.ical4j.data.CalendarBuilder$ContentHandlerImpl.startProperty(CalendarBuilder.java:326)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(CalendarParserImpl.java:245)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.access$1100(CalendarParserImpl.java:229)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:210)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:422)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$900(CalendarParserImpl.java:406)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:208)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:115)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:180)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:149)
	... 26 more
```
