### ISSUE TITLE
2.0.3 dexing error on Android

### ISSUE THREAD

**Issue by rfc2822** [ical4j/ical4j#180]
Since 2.0.3, I get the following message from Android build tools when using ical4j:

    com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex '/home/...../.gradle/caches/modules-2/files-2.1/org.mnode.ical4j/ical4j/2.0.3/f6ea66361afd3895a324dba60f625368d7047c51/ical4j-2.0.3.jar' to '/home/ricki/Entwicklung/davdroid/app/build/intermediates/pre-dexed/standard/debug/ical4j-2.0.3_e96b12a9ac5b33dd1889ac36fbe494d89963573f.jar'

When trying to dex it manually:
```
~/opt/android-sdk/build-tools/26.0.1/dx --verbose --dex /home/...../.gradle/caches/modules-2/files-2.1/org.mnode.ical4j/ical4j/2.0.3/f6ea66361afd3895a324dba60f625368d7047c51/ical4j-2.0.3.jar
processing archive /home/ricki/.gradle/caches/modules-2/files-2.1/org.mnode.ical4j/ical4j/2.0.3/f6ea66361afd3895a324dba60f625368d7047c51/ical4j-2.0.3.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource META-INF/services/
ignored resource META-INF/services/net.fortuna.ical4j.model.ComponentFactory
ignored resource META-INF/services/net.fortuna.ical4j.model.ParameterFactory
ignored resource META-INF/services/net.fortuna.ical4j.model.PropertyFactory
ignored resource META-INF/services/net.fortuna.ical4j.transform.rfc5545.Rfc5545ComponentRule
ignored resource META-INF/services/net.fortuna.ical4j.transform.rfc5545.Rfc5545PropertyRule
ignored resource META-INF/services/net.fortuna.ical4j.validate.CalendarValidatorFactory
ignored resource META-INF/services/org.codehaus.groovy.runtime.ExtensionModule
ignored resource net/
ignored resource net/fortuna/
ignored resource net/fortuna/ical4j/
ignored resource net/fortuna/ical4j/data/
ignored resource net/fortuna/ical4j/data/package-info.java
processing net/fortuna/ical4j/data/AbstractOutputter.class...
processing net/fortuna/ical4j/data/CalendarBuilder.class...
processing net/fortuna/ical4j/data/CalendarBuilder$ContentHandlerImpl.class...
processing net/fortuna/ical4j/data/CalendarOutputter.class...
processing net/fortuna/ical4j/data/CalendarParser.class...
processing net/fortuna/ical4j/data/CalendarParserFactory.class...
processing net/fortuna/ical4j/data/CalendarParserImpl.class...
processing net/fortuna/ical4j/data/CalendarParserImpl$1.class...
processing net/fortuna/ical4j/data/CalendarParserImpl$ComponentListParser.class...
processing net/fortuna/ical4j/data/CalendarParserImpl$ComponentParser.class...
processing net/fortuna/ical4j/data/CalendarParserImpl$ParameterListParser.class...
processing net/fortuna/ical4j/data/CalendarParserImpl$ParameterParser.class...
[…]
ignored resource zoneinfo/Pacific/Wallis.ics
ignored resource zoneinfo/zones.h
ignored resource zoneinfo/zones.tab
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lnet/fortuna/ical4j/groovy/DurExtension;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lnet/fortuna/ical4j/groovy/PeriodExtension;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lnet/fortuna/ical4j/model/CalendarFactory;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lnet/fortuna/ical4j/model/ContentBuilder;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lnet/fortuna/ical4j/model/ParameterListFactory;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lnet/fortuna/ical4j/model/component/AbstractComponentFactory;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lnet/fortuna/ical4j/model/component/AvailableFactory;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lnet/fortuna/ical4j/model/component/DaylightFactory;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lnet/fortuna/ical4j/model/component/StandardFactory;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:615)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:313)
```

So ical4j/2.0.3 can't be used with Android. Has something in the build process been changed which could cause these errors? I guess it means there are classes with the same name in different class files (collision), so that the dexer doesn't know which ones to take.

2.0.2 seems to work fine.

**Comment by benfortuna** [comment]
There shouldn't be a major difference from 2.0.2. 

In fact I've just tried running dex on my local to confirm the error you are seeing with the artefact from maven central. I've also rebuilt from source and it works fine. 

I'll try generating a new release, which will hopefully fix the issue.

**Comment by benfortuna** [comment]
Pls try again with the new release just published: https://bintray.com/ical4j/maven/ical4j/2.0.4

It might take an hour or two to appear in maven central.

**Comment by rfc2822** [comment]
Cool, 2.0.4 works again! Thanks!
