### ISSUE TITLE
CalendarBuilder crash with big files

### ISSUE THREAD

**Issue by cgprada** [ical4j/ical4j#183]
Hi everyone.

I'm using the version 2.0.0 of the ICal4j to build a Calendar from a file that contains more than 90.000 of Ical events. The size of the file is 427 MB. When my code tries to build the calendar from a FileInputStream it crashes. 

Do you know if the CalendarBuilder object has some restrictions regarding to the size of files? Do you know any configuration that helps me to avoid this problem?

**Fragment of My Code**

`if (fin != null) {

			final String KEY_RELAXED_PARSING = "ical4j.parsing.relaxed";
			final String KEY_RELAXED_UNFOLDING = "ical4j.unfolding.relaxed";
			
			CompatibilityHints.setHintEnabled(KEY_RELAXED_PARSING, true);
			CompatibilityHints.setHintEnabled(KEY_RELAXED_UNFOLDING, true);
						
			CalendarBuilder builder = new CalendarBuilder();
			net.fortuna.ical4j.model.Calendar calendar = null;
			
			try {
				LOG.info("Starting to build the calendar.");
				calendar = builder.build(fin);
				LOG.info("- Calendar Builded!.");
				
			} catch (IOException e) {

				LOG.error("Error Importing Events From File", e);
				e.printStackTrace();

			} catch (ParserException e) {

				LOG.error("Error Importing Events From File", e);
				e.printStackTrace();

			} catch (Exception e) {

				LOG.error("Error Importing Events From File", e);
				e.printStackTrace();
			}
`

**Error Trace**	

INFO   | jvm 1    | 2017/08/30 16:40:45 |    java.lang.Thread.State: RUNNABLE
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarParserImpl.nextToken(CalendarParserImpl.java:632)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarParserImpl.nextToken(CalendarParserImpl.java:618)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarParserImpl.assertToken(CalendarParserImpl.java:460)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarParserImpl.access$700(CalendarParserImpl.java:56)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarParserImpl$ParameterParser.parse(CalendarParserImpl.java:328)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarParserImpl$ParameterParser.access$1800(CalendarParserImpl.java:322)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarParserImpl$ParameterListParser.parse(CalendarParserImpl.java:310)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(CalendarParserImpl.java:247)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.access$1100(CalendarParserImpl.java:229)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:210)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:422)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$900(CalendarParserImpl.java:406)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:208)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:115)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:180)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:149)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:198)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:178)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:165)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at com.blackboard.consulting.geci.service.impl.ICalIntegrationServiceImpl.getCalInfoFromIcsFile(ICalIntegrationServiceImpl.java:670)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at com.blackboard.consulting.geci.service.impl.ICalIntegrationServiceImpl.importCalendarEventsFromFile(ICalIntegrationServiceImpl.java:322)
INFO   | jvm 1    | 2017/08/30 16:40:45 | 	at com.blackboard.consulting.geci.job.FtpICalIntegratorJob.execute(FtpICalIntegratorJob.java:40)

Thank you very much for your help

Best Regards.

**Comment by benfortuna** [comment]
I must admit I haven't tried parsing such a large file before. I would suspect it may be running out of memory as it tries to load the entire file.

The stack trace doesn't appear to have much information, you may want to remove all the try/catch blocks just to see what the actual error was. Just throw exception of you need to.

I will see if I can reproduce the issue.

**Comment by douglm** [comment]
If you've enough disk try

|-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/atlassian/jira/ |

which will give you a good idea of what is eating up memory
