### ISSUE TITLE
IllegalArgumentException happens when try decompose VCal from Huawei P10 Lite 

### ISSUE THREAD

**Issue by duyanhbk93tn** [ical4j/ical4j#197]
Hello #benfortuna,
Can you help check this problem? 

From Huawei P10 Lite device, create an event with Repeat: Yearly.
In exported file, it saved as below:
 RRULE:YD1 #0

When decompose I got:

net.fortuna.ical4j.data.ParserException 
net.fortuna.ical4j.data.ParserException: Error at line 12:Missing expected token, last token: YD1 #0
                      at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:143)

 Caused by: java.lang.IllegalArgumentException: Missing expected token, last token: YD1 #0
                   at net.fortuna.ical4j.model.Recur.nextToken(Recur.java:251)
                   at net.fortuna.ical4j.model.Recur.<init>(Recur.java:237)
                   at net.fortuna.ical4j.model.property.RRule.setValue(RRule.java:112)
                   at net.fortuna.ical4j.data.CalendarBuilder$ContentHandlerImpl.propertyValue(CalendarBuilder.java:299)
                   at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(CalendarParserImpl.java:243)

**Comment by benfortuna** [comment]
Can you provide a complete sample file to test with? I can't see if the error was on the same line as the RRULE (i.e. line 12).

**Comment by duyanhbk93tn** [comment]
Here is sample file:

BEGIN:VCALENDAR
VERSION:1.0
TZ:+00:00
BEGIN:VEVENT
COMPLETED:19700101T000000Z
DTSTART:20171014T070000Z
CLASS:PUBLIC
DTEND:20171014T080000Z
DESCRIPTION;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:Hello
SUMMARY;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:Titl
RRULE:YD1 #0
STATUS:TENTATIVE
AALARM:20171014T065000;;;
EVENTCALENDARTYPE:SOLAR
END:VEVENT
END:VCALENDAR
