### ISSUE TITLE
NPE in TimeZoneRegistryImpl.java:92 (due to missing tz.alias)

### ISSUE THREAD

**Issue by malkusch** [ical4j/ical4j#201]
java.lang.NullPointerException: null
	at java.util.Properties$LineReader.readLine(Properties.java:434) ~[na:1.8.0_152]
	at java.util.Properties.load0(Properties.java:353) ~[na:1.8.0_152]
	at java.util.Properties.load(Properties.java:341) ~[na:1.8.0_152]
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<clinit>(TimeZoneRegistryImpl.java:92) ~[ical4j-2.1.3.jar:na]

I see a tz.alias in /net/fortuna/ical4j/model/tz.alias, but a [`getResourceAsStream("tz.alias")`](https://github.com/ical4j/ical4j/blob/ical4j-2.1.3/src/main/java/net/fortuna/ical4j/model/TimeZoneRegistryImpl.java#L91) returns null.

**Comment by malkusch** [comment]
On a site note, scanning through your issues I get the impression there are quiet some problems around your timezone implementation. Wouldn't it be easier to outsource that sub domain to e.g. java.time and not bother with that at all?

**Comment by rfc2822** [comment]
@malkusch You can work around this by creating an empty `tz.alias` resource file.
