### ISSUE TITLE
Crash when parsing on Android

### ISSUE THREAD

**Issue by magneticflux-** [ical4j/ical4j#208]
```
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/cache/Caching;
   at net.fortuna.ical4j.util.JCacheTimeZoneCache.<init>(JCacheTimeZoneCache.java:15)
   at net.fortuna.ical4j.model.TimeZoneLoader$2.get(TimeZoneLoader.java:283)
   at net.fortuna.ical4j.model.TimeZoneLoader$2.get(TimeZoneLoader.java:280)
   at net.fortuna.ical4j.util.Optional.orElseGet(Optional.java:31)
   at net.fortuna.ical4j.model.TimeZoneLoader.cacheInit(TimeZoneLoader.java:280)
   at net.fortuna.ical4j.model.TimeZoneLoader.<init>(TimeZoneLoader.java:80)
   at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<init>(TimeZoneRegistryImpl.java:125)
   at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<init>(TimeZoneRegistryImpl.java:116)
   at net.fortuna.ical4j.model.DefaultTimeZoneRegistryFactory.createRegistry(DefaultTimeZoneRegistryFactory.java:48)
   at net.fortuna.ical4j.data.CalendarBuilder.<init>(CalendarBuilder.java:105)
```

It appears I need to add the line `
-keep,includedescriptorclasses class net.fortuna.ical4j.util.MapTimeZoneCache` to my ProGuard file and the line `net.fortuna.ical4j.timezone.cache.impl=net.fortuna.ical4j.util.MapTimeZoneCache` to my `app/main/resources/ical4j.properties` file.

You should probably note that in the Android section.

**Comment by w0yne** [comment]
I think it's kind of related to:
https://github.com/ical4j/ical4j/issues/195#issuecomment-341607240
