### ISSUE TITLE
v2.1.5 fails with java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by ItsNotYou** [ical4j/ical4j#215]
When trying to parse an iCal file with
```
<dependency>
	<groupId>org.mnode.ical4j</groupId>
	<artifactId>ical4j</artifactId>
	<version>2.1.5</version>
</dependency>
```
```
Calendar cal = new CalendarBuilder().build(new URL(iCalBase + iCalId).openStream());
```
the process fails, resulting in the exception
```
java.lang.NoClassDefFoundError: javax/cache/configuration/Configuration
	at net.fortuna.ical4j.model.TimeZoneLoader$2.get(TimeZoneLoader.java:287)
	at net.fortuna.ical4j.model.TimeZoneLoader$2.get(TimeZoneLoader.java:284)
	at net.fortuna.ical4j.util.Optional.orElseGet(Optional.java:31)
	at net.fortuna.ical4j.model.TimeZoneLoader.cacheInit(TimeZoneLoader.java:284)
	at net.fortuna.ical4j.model.TimeZoneLoader.<init>(TimeZoneLoader.java:80)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<init>(TimeZoneRegistryImpl.java:125)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<init>(TimeZoneRegistryImpl.java:116)
	at net.fortuna.ical4j.model.DefaultTimeZoneRegistryFactory.createRegistry(DefaultTimeZoneRegistryFactory.java:48)
	at net.fortuna.ical4j.data.CalendarBuilder.<init>(CalendarBuilder.java:105)
	at [... omitted] 
Caused by: java.lang.ClassNotFoundException: javax.cache.configuration.Configuration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more

```
The problem doesn't occur with ical4j 2.0.5, the complete URL is [https://www.uni-potsdam.de/veranstaltungen/detail/event/iCalExport.html?tx_upevents_upeventshow%5Buid%5D=2343](https://www.uni-potsdam.de/veranstaltungen/detail/event/iCalExport.html?tx_upevents_upeventshow%5Buid%5D=2343).

**Comment by benfortuna** [comment]
Yes, later versions include timezone caching, however you can override the jcache dependency by following instructions in this comment:

https://github.com/ical4j/ical4j/issues/195#issuecomment-341607240
