### ISSUE TITLE
Unsupported parameter name: FILENAME

### ISSUE THREAD

**Issue by cyberoblivion** [ical4j/ical4j#222]
Trying to import a calendar from google I receive exception when event has attached file.

VEVENT looks like this 

BEGIN:VEVENT
DTSTART;VALUE=DATE:20170601
DTEND;VALUE=DATE:20170602
RRULE:FREQ=MONTHLY;INTERVAL=3;BYMONTHDAY=1
DTSTAMP:20180215T170241Z
ORGANIZER;CN=CIM Calendar:mailto:XXX.com_75hd9cj5qnmm2il33hsu7cpps8@grou
 p.calendar.google.com
UID:XXXXg@google.com
CREATED:20170512T173944Z
DESCRIPTION:-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~
 :~:~:~:~:~:~:~:~::~:~::-\nPlease do not edit this section of the descriptio
 n.\n\n-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:
 ~:~:~:~:~:~:~:~:~:~::~:~::-
LAST-MODIFIED:20180201T155251Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Do work
TRANSP:TRANSPARENT
ATTACH;FILENAME=Do work xx-xx-xx.docx:https://drive.google
 .com/a/xxx.com/file/d/0B6gb-XZ9hQAXSW5/
 view?usp=drive_web
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-P0DT0H10M0S
END:VALARM
END:VEVENT

exception was:

net.fortuna.ical4j.data.ParserException: Error at line 6,068:Unsupported parameter name: FILENAME
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:158)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:198)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:178)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:165)
	at com.ciminc.ical.Main.main(Main.java:39)
Caused by: java.lang.IllegalArgumentException: Unsupported parameter name: FILENAME
	at net.fortuna.ical4j.model.ParameterFactoryImpl.createParameter(ParameterFactoryImpl.java:92)
	at net.fortuna.ical4j.data.CalendarBuilder$ContentHandlerImpl.parameter(CalendarBuilder.java:273)
	at net.fortuna.ical4j.data.CalendarParserImpl$ParameterParser.parse(CalendarParserImpl.java:367)
	at net.fortuna.ical4j.data.CalendarParserImpl$ParameterParser.access$1800(CalendarParserImpl.java:322)
	at net.fortuna.ical4j.data.CalendarParserImpl$ParameterListParser.parse(CalendarParserImpl.java:310)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(CalendarParserImpl.java:247)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.access$1100(CalendarParserImpl.java:229)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:210)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:422)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$900(CalendarParserImpl.java:406)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:208)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:115)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:180)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:149)

**Comment by benfortuna** [comment]
I've added the FILENAME parameter to ical4j-extensions library, so once it's released just include in your classpath and it should resolve the issue. https://github.com/ical4j/ical4j-extensions/pull/23

**Comment by benfortuna** [comment]
Fix applied. Closing issue.
