### ISSUE TITLE
Upgrade from 1.x to 2.1.0

### ISSUE THREAD

**Issue by tarunvrma** [ical4j/ical4j#238]
When i was trying to upgrade ical4j from 1.x to 2.1.0 but i am getting the following issues. Could you help us out what exactly the issues are?

Issue #1
[2018-05-16 14:08:13,245] [main] TimeZoneRegistryImpl WARN - Error occurred loading VTimeZone
java.lang.NullPointerException: dayOfWeek must not be null
at org.threeten.bp.jdk8.Jdk8Methods.requireNonNull(Jdk8Methods.java:79)
at org.threeten.bp.temporal.TemporalAdjusters.firstInMonth(TemporalAdjusters.java:262)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.addTransitionRules(TimeZoneRegistryImpl.java:371)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.generateTimezoneForId(TimeZoneRegistryImpl.java:342)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.loadVTimeZone(TimeZoneRegistryImpl.java:254)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.getTimeZone(TimeZoneRegistryImpl.java:213)

​

Issue #2
2018-05-16 14:08:13,687] [main] TimeZoneRegistryImpl WARN - **Error occurred loading VTimeZone
java.util.NoSuchElementException**
at java.util.Collections$EmptyIterator.next(Collections.java:4189)
at java.util.Collections.min(Collections.java:635)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.addTransitionRules(TimeZoneRegistryImpl.java:352)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.generateTimezoneForId(TimeZoneRegistryImpl.java:342)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.loadVTimeZone(TimeZoneRegistryImpl.java:254)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.getTimeZone(TimeZoneRegistryImpl.java:213)

Similar to issue 2
[2018-05-16 14:08:13,682] [main] TimeZoneRegistryImpl WARN - Error occurred loading VTimeZone
java.util.NoSuchElementException
at java.util.ArrayList$Itr.next(ArrayList.java:862)
at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
at java.util.Collections.min(Collections.java:635)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.addTransitionRules(TimeZoneRegistryImpl.java:352)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.generateTimezoneForId(TimeZoneRegistryImpl.java:342)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.loadVTimeZone(TimeZoneRegistryImpl.java:254)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.getTimeZone(TimeZoneRegistryImpl.java:213)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.getTimeZone(TimeZoneRegistryImpl.java:206)

Issue #3
[2018-05-16 14:08:13,674] [main] TimeZoneRegistryImpl WARN - Error occurred loading VTimeZone
org.threeten.bp.zone.ZoneRulesException: Unknown time-zone ID: SystemV/YST9YDT
at org.threeten.bp.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:167)
at org.threeten.bp.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:122)
at org.threeten.bp.ZoneRegion.ofId(ZoneRegion.java:143)
at org.threeten.bp.ZoneId.of(ZoneId.java:358)
at org.threeten.bp.ZoneId.of(ZoneId.java:286)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.generateTimezoneForId(TimeZoneRegistryImpl.java:332)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.loadVTimeZone(TimeZoneRegistryImpl.java:254)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.getTimeZone(TimeZoneRegistryImpl.java:213)

Similar to issue 3
[2018-05-16 14:08:13,666] [main] TimeZoneRegistryImpl WARN - Error occurred loading VTimeZone
org.threeten.bp.zone.ZoneRulesException: Unknown time-zone ID: SystemV/MST7MDT
at org.threeten.bp.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:167)
at org.threeten.bp.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:122)
at org.threeten.bp.ZoneRegion.ofId(ZoneRegion.java:143)
at org.threeten.bp.ZoneId.of(ZoneId.java:358)
at org.threeten.bp.ZoneId.of(ZoneId.java:286)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.generateTimezoneForId(TimeZoneRegistryImpl.java:332)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.loadVTimeZone(TimeZoneRegistryImpl.java:254)
at net.fortuna.ical4j.model.TimeZoneRegistryImpl.getTimeZone(TimeZoneRegistryImpl.java:213)

Similar to issue 3
[2018-05-16 14:08:13,663] [main] TimeZoneRegistryImpl WARN - Error occurred loading VTimeZone
org.threeten.bp.zone.ZoneRulesException: Unknown time-zone ID: SystemV/HST10
at org.threeten.bp.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:167)
at org.threeten.bp.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:122)
at org.threeten.bp.ZoneRegion.ofId(ZoneRegion.java:143)
at org.threeten.bp.ZoneId.of(ZoneId.java:358)
at org.threeten.bp.ZoneId.of(ZoneId.java:286)

**Comment by benfortuna** [comment]
It looks like some of those issues may be caused by the non-standard timezone id:

 SystemV/YST9YDT

If you can share an example calendar file it may help to diagnose the issues.

**Comment by benfortuna** [comment]
I expect there will be some errors as there isn't a direct correlation between TimeZone.getAvailableIDs() and the include VTIMEZONE definitions.

Where you are seeing the errors is I believe where it's trying to derive a timezone definition, however I would expect only the standard timezones (e.g. Continent/City) to work.

**Comment by tarunvrma** [comment]
I dont think there are any other errors. Majority of timezone are not raising any exception but few timezones have problem. I was trying to debug the code and for couple of timezone which are City. Here are the values being passed and in threeten code the exception is raising.
`addTransitionRules(ZoneId zoneId, int rawTimeZoneOffsetInSeconds, VTimeZone result) `

Etc/GMT
zoneID = Etc/GMT+0, 
rawTimeZoneOffsetInSeconds = 0,
result = BEGIN:VTIMEZONE
		 TZID:Etc/GMT+0
		 END:VTIMEZONE



zoneID = Asia/Tehran, 
rawTimeZoneOffsetInSeconds = 12600,
result = BEGIN:VTIMEZONE
		TZID:Asia/Tehran
		BEGIN:DAYLIGHT
		DTSTART:19771101T000000
		TZOFFSETFROM:+0330
		TZOFFSETTO:+0400
		RDATE:19771101T000000
		END:DAYLIGHT
		BEGIN:STANDARD
		DTSTART:19790101T000000
		TZOFFSETFROM:+0400
		TZOFFSETTO:+0330
		RDATE:19790101T000000
		END:STANDARD
		BEGIN:STANDARD
		DTSTART:19460101T000000
		TZOFFSETFROM:+032544
		TZOFFSETTO:+0330
		RDATE:19460101T000000
		END:STANDARD
		BEGIN:DAYLIGHT
		DTSTART:19790321T000000
		TZOFFSETFROM:+0330
		TZOFFSETTO:+0430
		RDATE:19910503T000000
		RDATE:19990322T000000
		RDATE:19920322T000000
		RDATE:19790321T000000
		RDATE:19800321T000000
		RDATE:19930322T000000
		RDATE:19940322T000000
		RDATE:19950322T000000
		RDATE:19970322T000000
		RDATE:19980322T000000
		RDATE:20010322T000000
		RDATE:20020322T000000
		RDATE:20050322T000000
		RDATE:20090322T000000
		RDATE:20100322T000000
		RDATE:20130322T000000
		RDATE:20140322T000000
		RDATE:20150322T000000
		RDATE:20110322T000000
		RDATE:20030322T000000
		RDATE:20210322T000000
		RDATE:20170322T000000
		RDATE:20180322T000000
		RDATE:20190322T000000
		RDATE:20220322T000000
		RDATE:20230322T000000
		RDATE:20250322T000000
		RDATE:20260322T000000
		RDATE:20300322T000000
		RDATE:20340322T000000
		RDATE:20350322T000000
		RDATE:20310322T000000
		RDATE:20270322T000000
		RDATE:20290321T000000
		RDATE:20160321T000000
		RDATE:20200321T000000
		RDATE:20240321T000000
		RDATE:20280321T000000
		RDATE:20320321T000000
		RDATE:20330321T000000
		RDATE:20360321T000000
		RDATE:20370321T000000
		RDATE:19960321T000000
		RDATE:20000321T000000
		RDATE:20040321T000000
		RDATE:20080321T000000
		RDATE:20120321T000000
		END:DAYLIGHT
		BEGIN:STANDARD
		DTSTART:19790919T000000
		TZOFFSETFROM:+0430
		TZOFFSETTO:+0330
		RDATE:19980922T000000
		RDATE:19950922T000000
		RDATE:19910922T000000
		RDATE:19920922T000000
		RDATE:19930922T000000
		RDATE:19940922T000000
		RDATE:19970922T000000
		RDATE:19990922T000000
		RDATE:20010922T000000
		RDATE:20020922T000000
		RDATE:20050922T000000
		RDATE:20090922T000000
		RDATE:20100922T000000
		RDATE:20130922T000000
		RDATE:20140922T000000
		RDATE:20150922T000000
		RDATE:20110922T000000
		RDATE:20030922T000000
		RDATE:20210922T000000
		RDATE:20170922T000000
		RDATE:20180922T000000
		RDATE:20190922T000000
		RDATE:20220922T000000
		RDATE:20230922T000000
		RDATE:20250922T000000
		RDATE:20260922T000000
		RDATE:20300922T000000
		RDATE:20340922T000000
		RDATE:20350922T000000
		RDATE:20310922T000000
		RDATE:20270922T000000
		RDATE:20240921T000000
		RDATE:19800923T000000
		RDATE:20160921T000000
		RDATE:20200921T000000
		RDATE:20280921T000000
		RDATE:20290921T000000
		RDATE:20320921T000000
		RDATE:20330921T000000
		RDATE:20360921T000000
		RDATE:20370921T000000
		RDATE:19960921T000000	
		RDATE:20000921T000000
		RDATE:20040921T000000
		RDATE:20080921T000000
		RDATE:20120921T000000
		RDATE:19790919T000000
		END:STANDARD
		BEGIN:DAYLIGHT
		DTSTART:19780321T000000
		TZOFFSETFROM:+0400
		TZOFFSETTO:+0500
		RDATE:19780321T000000
		END:DAYLIGHT
		BEGIN:DAYLIGHT
		DTSTART:19781021T000000
		TZOFFSETFROM:+0500
		TZOFFSETTO:+0400
		RDATE:19781021T000000
		END:DAYLIGHT
		END:VTIMEZONE
I am not sure whether this will help you to investigate but if you need any other info, kindly let me know.

**Comment by tarunvrma** [comment]
I dont think there are any other errors. Majority of timezone are not raising any exception but few timezones have problem. I was trying to debug the code and for couple of timezone which are City. Here are the values being passed and in threeten code the exception is raising.
`addTransitionRules(ZoneId zoneId, int rawTimeZoneOffsetInSeconds, VTimeZone result) `

Etc/GMT
zoneID = Etc/GMT+0, 
rawTimeZoneOffsetInSeconds = 0,
result = BEGIN:VTIMEZONE
		 TZID:Etc/GMT+0
		 END:VTIMEZONE



zoneID = Asia/Tehran, 
rawTimeZoneOffsetInSeconds = 12600,
result = BEGIN:VTIMEZONE
		TZID:Asia/Tehran
		BEGIN:DAYLIGHT
		DTSTART:19771101T000000
		TZOFFSETFROM:+0330
		TZOFFSETTO:+0400
		RDATE:19771101T000000
		END:DAYLIGHT
		BEGIN:STANDARD
		DTSTART:19790101T000000
		TZOFFSETFROM:+0400
		TZOFFSETTO:+0330
		RDATE:19790101T000000
		END:STANDARD
		BEGIN:STANDARD
		DTSTART:19460101T000000
		TZOFFSETFROM:+032544
		TZOFFSETTO:+0330
		RDATE:19460101T000000
		END:STANDARD
		BEGIN:DAYLIGHT
		DTSTART:19790321T000000
		TZOFFSETFROM:+0330
		TZOFFSETTO:+0430
		RDATE:19910503T000000
		RDATE:19990322T000000
		RDATE:19920322T000000
		RDATE:19790321T000000
		RDATE:19800321T000000
		RDATE:19930322T000000
		RDATE:19940322T000000
		RDATE:19950322T000000
		RDATE:19970322T000000
		RDATE:19980322T000000
		RDATE:20010322T000000
		RDATE:20020322T000000
		RDATE:20050322T000000
		RDATE:20090322T000000
		RDATE:20100322T000000
		RDATE:20130322T000000
		RDATE:20140322T000000
		RDATE:20150322T000000
		RDATE:20110322T000000
		RDATE:20030322T000000
		RDATE:20210322T000000
		RDATE:20170322T000000
		RDATE:20180322T000000
		RDATE:20190322T000000
		RDATE:20220322T000000
		RDATE:20230322T000000
		RDATE:20250322T000000
		RDATE:20260322T000000
		RDATE:20300322T000000
		RDATE:20340322T000000
		RDATE:20350322T000000
		RDATE:20310322T000000
		RDATE:20270322T000000
		RDATE:20290321T000000
		RDATE:20160321T000000
		RDATE:20200321T000000
		RDATE:20240321T000000
		RDATE:20280321T000000
		RDATE:20320321T000000
		RDATE:20330321T000000
		RDATE:20360321T000000
		RDATE:20370321T000000
		RDATE:19960321T000000
		RDATE:20000321T000000
		RDATE:20040321T000000
		RDATE:20080321T000000
		RDATE:20120321T000000
		END:DAYLIGHT
		BEGIN:STANDARD
		DTSTART:19790919T000000
		TZOFFSETFROM:+0430
		TZOFFSETTO:+0330
		RDATE:19980922T000000
		RDATE:19950922T000000
		RDATE:19910922T000000
		RDATE:19920922T000000
		RDATE:19930922T000000
		RDATE:19940922T000000
		RDATE:19970922T000000
		RDATE:19990922T000000
		RDATE:20010922T000000
		RDATE:20020922T000000
		RDATE:20050922T000000
		RDATE:20090922T000000
		RDATE:20100922T000000
		RDATE:20130922T000000
		RDATE:20140922T000000
		RDATE:20150922T000000
		RDATE:20110922T000000
		RDATE:20030922T000000
		RDATE:20210922T000000
		RDATE:20170922T000000
		RDATE:20180922T000000
		RDATE:20190922T000000
		RDATE:20220922T000000
		RDATE:20230922T000000
		RDATE:20250922T000000
		RDATE:20260922T000000
		RDATE:20300922T000000
		RDATE:20340922T000000
		RDATE:20350922T000000
		RDATE:20310922T000000
		RDATE:20270922T000000
		RDATE:20240921T000000
		RDATE:19800923T000000
		RDATE:20160921T000000
		RDATE:20200921T000000
		RDATE:20280921T000000
		RDATE:20290921T000000
		RDATE:20320921T000000
		RDATE:20330921T000000
		RDATE:20360921T000000
		RDATE:20370921T000000
		RDATE:19960921T000000	
		RDATE:20000921T000000
		RDATE:20040921T000000
		RDATE:20080921T000000
		RDATE:20120921T000000
		RDATE:19790919T000000
		END:STANDARD
		BEGIN:DAYLIGHT
		DTSTART:19780321T000000
		TZOFFSETFROM:+0400
		TZOFFSETTO:+0500
		RDATE:19780321T000000
		END:DAYLIGHT
		BEGIN:DAYLIGHT
		DTSTART:19781021T000000
		TZOFFSETFROM:+0500
		TZOFFSETTO:+0400
		RDATE:19781021T000000
		END:DAYLIGHT
		END:VTIMEZONE
I am not sure whether this will help you to investigate but if you need any other info, kindly let me know.

**Comment by gkondayap** [comment]
Can we customize it to add custom timezones to VTIMEZONE definitions?  Or is it providing any configurable way to add new timezones to VTIMEZONE definitions?

**Comment by benfortuna** [comment]
For individual calendars you can create VTIMEZONE objects and add to your calendar.

If you want a timezone in the registry based on a custom VTIMEZONE you can register a new TimeZone instance with the registry using the register functions.

If you want the custom timezone to persist in your application you can implement a custom TimeZoneRegistry and override the property specifying which registry to use.

**Comment by gkondayap** [comment]
Thank you for your reply Ben.  I have upgraded ical4j-3.0.1.  I notice this error arises only for 2 timezones (Asia/Tehran , Iran).   Could  you please elaborate your suggested choices. 
I did't find a way to override any methods like register() in . Most of them are final methods.

**Comment by gkondayap** [comment]
Environment :
    OS: Ubuntu
    Java Version [jdk-1.8.0_181]
    ical4j-3.0.1

ERROR: java.lang.NullPointerException: dayOfWeek

    When we call TimeZoneRegistryImpl.getTimeZone(id) Asia/Tehran & Iran timezones, net.fortuna.ical4j.model.TimeZoneLoader.addTransitionRules() has below code. where transitionRuleDayOfWeek is coming as null for Asia/Tehran & Iran timezone. Current piece of code accessing it without checking not null condition.

DayOfWeek transitionRuleDayOfWeek = transitionRule.getDayOfWeek();
LocalDateTime ldt = LocalDateTime.now(zoneId)
.with(TemporalAdjusters.firstInMonth(transitionRuleDayOfWeek))
.withMonth(transitionRuleMonthValue)
.with(transitionRule.getLocalTime());

    JDK8 declared that DayOfWeek can be null in java.time.zone.ZoneOffsetTransitionRule
    /**
        The cutover day-of-week, null to retain the day-of-month.
        */
        private final DayOfWeek dow;

    We are expecting valid vtimezone for Asia/Tehran & Iran without error.
