### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Optional;

### ISSUE THREAD

**Issue by leventepal** [ical4j/ical4j#269]
**Describe the bug**
I'm using the library as a compiled .jar in Android, everything works fine, but on Android 6.0 or lower, the "Optional" class doesn't exists. It's because of Android's JVM doesn't have Java 8's features.

**To Reproduce**
1. Include the ical4j as a dependency in your Java project
2. Build the artifcat (exporting .jar)
3. Integrate the .jar file into your Android project
4. Launch the application on an Android 6.0 or lower

**Expected behavior**
The library should be backward compatible.

**Environment (please complete the following information):**
 - OS: Android
 - Java Version 7

**Additional context**
The stacktrace:

`Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Optional;
        at net.fortuna.ical4j.util.Configurator.getProperty(Configurator.java:80)
        at net.fortuna.ical4j.util.CompatibilityHints.<clinit>(CompatibilityHints.java:87)
        at net.fortuna.ical4j.util.CompatibilityHints.isHintEnabled(CompatibilityHints.java:124)
        at net.fortuna.ical4j.model.Iso8601.<init>(Iso8601.java:78)
        at net.fortuna.ical4j.model.Date.<init>(Date.java:150)
        at net.fortuna.ical4j.model.DateTime.<init>(DateTime.java:262)`

Could you replace the "Optional" class with something Java 7 compatible?

**Comment by rfc2822** [comment]
See #246

**Comment by benfortuna** [comment]
As mentioned in linked issue, please use ical4j 2.x for Java 7 support. Closing issue.
