### ISSUE TITLE
Documentation / Support Request

### ISSUE THREAD

**Issue by FredFirestone** [ical4j/ical4j#29]
I've modified davdroid on android which is using ical4j. Unfortunately parsing my calendar entries yields XComponents and all properties are XProperties.

Thus I get massive errors using it, like class cast exceptions on .getUid() which leads me to assume the factory creation process is not working as intended.

Is there anything I am missing? Any configuration to influcence which properties are created?

**Comment by benfortuna** [comment]
Do you have a sample calendar file to demonstrate the issue? ical4j should only create XComponents/XProperties when it can't identify an appropriate factory.

**Comment by rfc2822** [comment]
I have the same problem.

When I use this gradle dependency in our Android project:

```
    /*compile('org.mnode.ical4j:ical4j:2.0-alpha1') {
        // we don't need content builders, see https://github.com/ical4j/ical4j/wiki/Groovy
        exclude group: 'org.codehaus.groovy', module: 'groovy-all'
    }*/
    compile 'org.slf4j:slf4j-android:1.7.12'       // slf4j is used by ical4j
```

then everything works. When compiling ical4j-master with `gradle jar` and using it:

```
    compile files('../lib/ical4j-master-20150729.jar')
    // dependencies for pre-compiled ical4j jar:
    compile 'biz.aQute.bnd:bndlib:2.3.0'
    compile 'commons-codec:commons-codec:1.10'
    compile 'org.slf4j:jcl-over-slf4j:1.7.12'
    compile 'org.slf4j:slf4j-android:1.7.12'       // slf4j is used by ical4j
```

then ical4j can't load time zones anymore.

```
final static TimeZoneRegistry tzRegistry = TimeZoneRegistryFactory.getInstance().createRegistry();
…
TimeZone tz = tzRegistry.getTimeZone("Europe/Vienna");
```

returns `null` because of this error:

```
07-29 22:32:30.118    6350-6371/at.bitfire.davdroid:sync W/TimeZoneRegistryImpl﹕ Error occurred loading VTimeZone
    java.lang.ClassCastException: net.fortuna.ical4j.model.component.XComponent cannot be cast to net.fortuna.ical4j.model.component.VTimeZone
            at net.fortuna.ical4j.model.TimeZoneRegistryImpl.loadVTimeZone(TimeZoneRegistryImpl.java:238)
            at net.fortuna.ical4j.model.TimeZoneRegistryImpl.getTimeZone(TimeZoneRegistryImpl.java:205)
            at at.bitfire.davdroid.resource.LocalCalendarTest.testBuildEntry(LocalCalendarTest.java:141)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
            at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
            at junit.framework.TestCase.runBare(TestCase.java:134)
            at junit.framework.TestResult$1.protect(TestResult.java:115)
            at junit.framework.TestResult.runProtected(TestResult.java:133)
            at junit.framework.TestResult.run(TestResult.java:118)
            at junit.framework.TestCase.run(TestCase.java:124)
            at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
            at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
            at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
            at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1729)
```

I guess that some factory is missing (as you said), but I don't know why? Classes for all the factories are in the .jar file, and ProGuard is not active for debug builds.

**Comment by benfortuna** [comment]
Since the last release (ical4j-2.0-alpha1) I have refactored the registration of factories to reduce code duplication and make it a bit more extensible. To do this I am using the java.util.ServiceLoader, which relies on resource files in the META-INF/services directory.

I suspect what is happening is that the META-INF/services folder isn't being packaged into the APK, and so the factories aren't being registered properly. This would explain why all the components are XComponents and properties are XProperties. I found a bug report on the ApkBuilder that strips the META-INF directory, which may be the cause depending on how you are building the APK:

https://code.google.com/p/android/issues/detail?id=59658

I haven't tried to build an APK from the latest ical4j code so I may be off the mark, but it sounds like the Gradle based build doesn't have this issue. Would you be able to confirm whether the META-INF/services directory is being packaged into your APK?

**Comment by FredFirestone** [comment]
Thank's for your efforts, you seem to have hit the issue: My apk does indeed not have the META-INF/services directory. 
I've likely not used gradle, so you may be right that Gradle based builds would not have this issue. Thanks again for getting to the bottom of this.

**Comment by op-and** [comment]
I am in the same situation. I am trying to parse the iCal below and am encountering the same problems with XProperties and XComponents. Ideally, I was hoping to be able to get 'EST' after the iCal is parsed. I tried adding the files manually, zipping the apk and resigning it, but android does not like the apk. I am using 2.0.1 beta jar. Any ideas/works-arounds would be appreciated.

BEGIN:VCALENDAR
PRODID:-//Microsoft Corporation//Outlook 10.0 MIMEDIR//EN
VERSION:2.0
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:Eastern Time
BEGIN:STANDARD
DTSTART:20131101T020000
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=1SU;BYMONTH=11
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
TZNAME:Standard Time
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:20130301T020000
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=2SU;BYMONTH=3
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
TZNAME:Daylight Savings Time
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ATTENDEE;CN="A B";ROLE=REQ-PARTICIPANT;RSVP=TRUE:MAILTO:ab@yahoo.com
ORGANIZER;CN="A C":MAILTO:ac@yahoo.com
DTSTART;TZID="Eastern Time":20150813T200453
DTEND;TZID="Eastern Time":20150813T201953
LOCATION:https://blackberry.webex.com/blackberry
TRANSP:OPAQUE
SEQUENCE:1439510693
UID:f9e4688f-4e92-405a-943a-a611ea8d8692
DTSTAMP:20150814T000453Z
DESCRIPTION:\nJOIN WEBEX MEETING\n
SUMMARY:test1
PRIORITY:5
CLASS:PUBLIC
END:VEVENT
END:VCALENDAR

**Comment by benfortuna** [comment]
I still don't have a solution for this, as I haven't had time to experiment with Android. Here is some more info about the issue and what other devs are trying (some successfully it seems):

http://stackoverflow.com/questions/5760607/using-serviceloader-on-android
