### ISSUE TITLE
Clarification: NumberFormatException vs ParserException

### ISSUE THREAD

**Issue by rfc2822** [ical4j/ical4j#313]
Currently, [parsing iCalendars with invalid values often throw a NumberFormatException](https://forums.bitfire.at/post/10939). For instance:

```
BEGIN:VEVENT
DTSTAMP:20190112T110842Z
CREATED:20190112T110818Z
UID:1111111111@booking.com
SEQUENCE:2
LAST-MODIFIED:20190112T110842Z
DESCRIPTION:Ankunft: Sonntag\, 28. Juli 2019\, anreise zwischen 15:30 - 21:
 00\n\nAbreise: Samstag\, 3. August 2019\, abreise zwischen 10:00 - 10:30\n
 \nSie können Ihre Buchung hier ansehen\, ändern oder stornieren
SUMMARY:Some Hotel
LOCATION:Puchen 209\, Altaussee\, 8992\, Austria
GEO:47.634239\;13.767147
DTSTART;VALUE=DATE:20190728
DTEND;VALUE=DATE:20190804
TRANSP:OPAQUE
CLASS:PRIVATE
END:VEVENT
```

causes

```
java.lang.NumberFormatException: For input string: "47634239\"
	at java.lang.Long.parseLong(Long.java:443)
	at java.lang.Long.parseLong(Long.java:485)
	at java.math.BigDecimal.<init>(BigDecimal.java:344)
	at java.math.BigDecimal.<init>(BigDecimal.java:425)
	at net.fortuna.ical4j.model.property.Geo.setValue(Geo.java:211)
	at net.fortuna.ical4j.data.CalendarBuilder$ContentHandlerImpl.propertyValue(CalendarBuilder.java:299)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(CalendarParserImpl.java:282)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.access$1100(CalendarParserImpl.java:229)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:210)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:422)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$900(CalendarParserImpl.java:406)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:208)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:115)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:180)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:149)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:198)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:178)
	at at.bitfire.ical4android.Event$Companion.fromReader(Event.kt:78)
```

I wonder whether this

1. is intended behavior – in this case, it should be documented in `CalenderBuilder.build` JavaDoc that these methods `@throws IllegalArgumentException` or `NumberFormatException`. I could send a merge request for that. _or_
2. should be wrapped in a `ParserException`, but then this would apply to all operations that could throw an `IllegalArgumentException`

**Comment by benfortuna** [comment]
Perhaps we could use the role that any checked exceptions are wrapper in ParserException and unchecked exceptions (illegal argument, number format, etc) need to be handled in application code.

For this we probably need to document accurately the unchecked exceptions so they can be handled..

**Comment by sbechet** [comment]
+1

Example:

`GEO:12.345678\;-1.234587` 

->

```
Caused by: java.lang.NumberFormatException: For input string: "12345678\"
        at java.lang.Long.parseLong(Long.java:594)
        at java.lang.Long.parseLong(Long.java:636)
        at java.math.BigDecimal.<init>(BigDecimal.java:344)
        at java.math.BigDecimal.<init>(BigDecimal.java:425)
        at net.fortuna.ical4j.model.property.Geo.setValue(Geo.java:214)
```

**Comment by sbechet** [comment]
Maybe unescape string forgotten like here?

```
aValue.substring(0, aValue.indexOf(';'));
...
```
