### ISSUE TITLE
Including ical4j as dependency breaks "gradle connectedCheck"

### ISSUE THREAD

**Issue by mbiebl** [ical4j/ical4j#315]
I'm trying to build `ical4android`, which uses `ical4j` internally.
The sources can be found at https://gitlab.com/bitfireAT/ical4android

While building ical4android works fine, but when I try to run `gradlew connectedCheck` it fails:
```
> Task :connectedDebugAndroidTest
02:46:10 V/ddms: execute: running am get-config
02:46:10 V/ddms: execute 'am get-config' on '59f17402' : EOF hit. Read: -1
02:46:10 V/ddms: execute: returning
02:46:10 D/ical4android-debug-androidTest.apk: Uploading ical4android-debug-androidTest.apk onto device '59f17402'
02:46:10 D/Device: Uploading file onto device '59f17402'
02:46:10 D/ddms: Reading file permision of /home/michael/git/ical4android/build/outputs/apk/androidTest/debug/ical4android-debug-androidTest.apk as: rw-r--r--
02:46:11 V/ddms: execute: running pm install -r -t "/data/local/tmp/ical4android-debug-androidTest.apk"
02:46:14 V/ddms: execute 'pm install -r -t "/data/local/tmp/ical4android-debug-androidTest.apk"' on '59f17402' : EOF hit. Read: -1
02:46:14 V/ddms: execute: returning
02:46:14 V/ddms: execute: running rm "/data/local/tmp/ical4android-debug-androidTest.apk"
02:46:14 V/ddms: execute 'rm "/data/local/tmp/ical4android-debug-androidTest.apk"' on '59f17402' : EOF hit. Read: -1
02:46:14 V/ddms: execute: returning
02:46:14 I/RemoteAndroidTest: Running am instrument -w -r   at.bitfire.ical4android.test/androidx.test.runner.AndroidJUnitRunner on SM-G900F - 8.1.0
02:46:14 V/ddms: execute: running am instrument -w -r   at.bitfire.ical4android.test/androidx.test.runner.AndroidJUnitRunner
02:46:17 V/InstrumentationResultParser: INSTRUMENTATION_RESULT: shortMsg=Process crashed.
02:46:17 I/InstrumentationResultParser: test run failed: 'Instrumentation run failed due to 'Process crashed.''
Starting 0 tests on SM-G900F - 8.1.0
Tests on SM-G900F - 8.1.0 failed: Instrumentation run failed due to 'Process crashed.'
02:46:17 I/XmlResultReporter: XML test result file generated at /home/michael/git/ical4android/build/outputs/androidTest-results/connected/TEST-SM-G900F - 8.1.0-ical4android-.xml. Total tests 0, 
02:46:17 V/InstrumentationResultParser: INSTRUMENTATION_CODE: 0
02:46:17 V/InstrumentationResultParser: 
02:46:17 V/ddms: execute 'am instrument -w -r   at.bitfire.ical4android.test/androidx.test.runner.AndroidJUnitRunner' on '59f17402' : EOF hit. Read: -1
02:46:17 V/ddms: execute: returning

com.android.builder.testing.ConnectedDevice > No tests found.[SM-G900F - 8.1.0] FAILED 
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).
02:46:17 I/XmlResultReporter: XML test result file generated at /home/michael/git/ical4android/build/outputs/androidTest-results/connected/TEST-SM-G900F - 8.1.0-ical4android-.xml. Total tests 1, failure 1, 
02:46:17 V/ddms: execute: running pm uninstall at.bitfire.ical4android.test
02:46:18 V/ddms: execute 'pm uninstall at.bitfire.ical4android.test' on '59f17402' : EOF hit. Read: -1
02:46:18 V/ddms: execute: returning

> Task :connectedDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':connectedDebugAndroidTest'.
> There were failing tests. See the report at: file:///home/michael/git/ical4android/build/reports/androidTests/connected/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8s
44 actionable tasks: 1 executed, 43 up-to-date
02:46:18: Task execution finished 'connectedCheck'.
```

I've attached a logcat output which shows lots of Groovy related class loading errors: 
[log.txt](https://github.com/ical4j/ical4j/files/2887279/log.txt)

The relevant part afaics is
```
02-21 02:46:16.704 13326 13341 E AndroidRuntime: FATAL EXCEPTION: Instr: androidx.test.runner.AndroidJUnitRunner
02-21 02:46:16.704 13326 13341 E AndroidRuntime: Process: at.bitfire.ical4android.test, PID: 13326
02-21 02:46:16.704 13326 13341 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lgroovy/util/AbstractFactory;
02-21 02:46:16.704 13326 13341 E AndroidRuntime: 	at java.lang.Class.classForName(Native Method)
02-21 02:46:16.704 13326 13341 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:453)
02-21 02:46:16.704 13326 13341 E AndroidRuntime: 	at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:72)
02-21 02:46:16.704 13326 13341 E AndroidRuntime: 	at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
02-21 02:46:16.704 13326 13341 E AndroidRuntime: 	at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:789)
02-21 02:46:16.704 13326 13341 E AndroidRuntime: 	at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:543)
02-21 02:46:16.704 13326 13341 E AndroidRuntime: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:386)
02-21 02:46:16.704 13326 13341 E AndroidRuntime: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2075)
02-21 02:46:16.704 13326 13341 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "groovy.util.AbstractFactory" on path: DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/at.bitfire.ical4android.test-ZObMEXNHLXwX1tCiWeko2A==/base.apk"],nativeLibraryDirectories=[/data/app/at.bitfire.ical4android.test-ZObMEXNHLXwX1tCiWeko2A==/lib/arm, /system/lib, /system/vendor/lib]]
02-21 02:46:16.704 13326 13341 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
02-21 02:46:16.704 13326 13341 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-21 02:46:16.704 13326 13341 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-21 02:46:16.704 13326 13341 E AndroidRuntime: 	... 8 more
02-21 02:46:16.708 13326 13341 I Process : Sending signal. PID: 13326 SIG: 9
```

I'd like to add here, that ical4android is not using any of the groovy related classes from ical4j.
For testing purposes, I locally built ical4j and simply removed all groovy bits via `rm -rf src/main/groovy/` and used the resulting `.jar` file. With that, `connectedCheck` passed successfully.

To reproduce the issue, run the following steps
```
git clone https://gitlab.com/bitfireAT/ical4android
cd ical4android
./gradlew connectedCheck
```

If ical4android is not using ical4j correctly, I would very much appreciate pointers on how this issue can be fixed.

Regards

**Environment (please complete the following information):**
 - OS:
Linux Debian sid
Android Studio 3.3.1
Android 8.1

 - Java Version
Java 8

**Comment by mbiebl** [comment]
https://gitlab.com/bitfireAT/ical4android/blob/master/build.gradle#L64
https://gitlab.com/bitfireAT/ical4android/tree/master/src/androidTest/java/at/bitfire/ical4android

**Comment by benfortuna** [comment]
Is it possibly related to using gradle 6, as I haven't tried building against this version.

Happy to update the groovy version or modify the classes if you can identify the cause. I notice we already have groovy as an optical dependency.

**Comment by rfc2822** [comment]
Can be worked around by adding:

    // groovy is not really used, but required for running the tests
    // noinspection GradleDependency
    androidTestImplementation 'org.codehaus.groovy:groovy:2.2.2'
