### ISSUE TITLE
Java 11 and iCal4j - org.apache.ignite.cache.CachingProvider could not be instantiated

### ISSUE THREAD

**Issue by mytechtoday** [ical4j/ical4j#319]
**Describe the bug**
After update to OpenJdk 11, When you are building the calendar instance with the CalendarBuilder, seeing the following 
```
Exception in thread "main" java.util.ServiceConfigurationError: javax.cache.spi.CachingProvider: Provider org.apache.ignite.cache.CachingProvider could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at javax.cache.Caching$CachingProviderRegistry$1.run(Caching.java:448)
	at javax.cache.Caching$CachingProviderRegistry$1.run(Caching.java:442)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javax.cache.Caching$CachingProviderRegistry.getCachingProviders(Caching.java:442)
	at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:380)
	at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:361)
	at javax.cache.Caching.getCachingProvider(Caching.java:151)
	at net.fortuna.ical4j.util.JCacheTimeZoneCache.<init>(JCacheTimeZoneCache.java:15)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at net.fortuna.ical4j.model.TimeZoneLoader.lambda$cacheInit$1(TimeZoneLoader.java:283)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at net.fortuna.ical4j.model.TimeZoneLoader.cacheInit(TimeZoneLoader.java:281)
	at net.fortuna.ical4j.model.TimeZoneLoader.<init>(TimeZoneLoader.java:85)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<init>(TimeZoneRegistryImpl.java:125)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<init>(TimeZoneRegistryImpl.java:116)
	at net.fortuna.ical4j.model.DefaultTimeZoneRegistryFactory.createRegistry(DefaultTimeZoneRegistryFactory.java:48)
	at net.fortuna.ical4j.data.CalendarBuilder.<init>(CalendarBuilder.java:77)
	at Test.main(Test.java:12)
Caused by: java.lang.ExceptionInInitializerError
	at org.apache.ignite.internal.util.IgniteUtils.<clinit>(IgniteUtils.java:765)
...
....
```

**To Reproduce**
```
import net.fortuna.ical4j.data.CalendarBuilder;
import net.fortuna.ical4j.data.ParserException;
import net.fortuna.ical4j.model.Calendar;

import java.io.IOException;
import java.io.StringReader;

public class Test {

    public static void main(String[] args) throws IOException, ParserException {

         Calendar monthly = new CalendarBuilder().build(new StringReader("BEGIN:VCALENDAR\n" +
                "BEGIN:VEVENT\n" +
                "DTSTAMP:20181024T153406Z\n" +
                "RRULE:FREQ=MONTHLY;INTERVAL=1;BYMONTHDAY=1\n" +
                "DTSTART;VALUE=DATE:20180101\n" +
                "DTEND;VALUE=DATE:20391231\n" +
                "END:VEVENT\n" +
                "END:VCALENDAR\n"));
        System.out.printf("monthly " + monthly);
    }
}

```

**Expected behavior**
 Should be able to see the calendar instance.

**Screenshots**
Getting the following error:
```

Exception in thread "main" java.util.ServiceConfigurationError: javax.cache.spi.CachingProvider: Provider org.apache.ignite.cache.CachingProvider could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at javax.cache.Caching$CachingProviderRegistry$1.run(Caching.java:448)
	at javax.cache.Caching$CachingProviderRegistry$1.run(Caching.java:442)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javax.cache.Caching$CachingProviderRegistry.getCachingProviders(Caching.java:442)
	at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:380)
	at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:361)
	at javax.cache.Caching.getCachingProvider(Caching.java:151)
	at net.fortuna.ical4j.util.JCacheTimeZoneCache.<init>(JCacheTimeZoneCache.java:15)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at net.fortuna.ical4j.model.TimeZoneLoader.lambda$cacheInit$1(TimeZoneLoader.java:283)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at net.fortuna.ical4j.model.TimeZoneLoader.cacheInit(TimeZoneLoader.java:281)
	at net.fortuna.ical4j.model.TimeZoneLoader.<init>(TimeZoneLoader.java:85)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<init>(TimeZoneRegistryImpl.java:125)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<init>(TimeZoneRegistryImpl.java:116)
	at net.fortuna.ical4j.model.DefaultTimeZoneRegistryFactory.createRegistry(DefaultTimeZoneRegistryFactory.java:48)
	at net.fortuna.ical4j.data.CalendarBuilder.<init>(CalendarBuilder.java:77)
	at Test.main(Test.java:12)
Caused by: java.lang.ExceptionInInitializerError
	at org.apache.ignite.internal.util.IgniteUtils.<clinit>(IgniteUtils.java:765)
	at org.apache.ignite.cache.CachingProvider.<clinit>(CachingProvider.java:53)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
	... 24 more
Caused by: java.lang.RuntimeException: jdk.internal.misc.JavaNioAccess class is unavailable.
	at org.apache.ignite.internal.util.GridUnsafe.javaNioAccessObject(GridUnsafe.java:1459)
	at org.apache.ignite.internal.util.GridUnsafe.<clinit>(GridUnsafe.java:118)
	... 31 more
Caused by: java.lang.IllegalAccessException: class org.apache.ignite.internal.util.GridUnsafe cannot access class jdk.internal.misc.SharedSecrets (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @f8c1ddd
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at org.apache.ignite.internal.util.GridUnsafe.javaNioAccessObject(GridUnsafe.java:1456)

```
**Environment (please complete the following information):**
 - OS: Window/linux
 - Java Version 11
    iCal4j-3.0.6

**Additional context**
You should be able simply reproduce the code, running the following :

`import net.fortuna.ical4j.data.CalendarBuilder;
import net.fortuna.ical4j.data.ParserException;
import net.fortuna.ical4j.model.Calendar;

import java.io.IOException;
import java.io.StringReader;

public class Test {

    public static void main(String[] args) throws IOException, ParserException {

         Calendar monthly = new CalendarBuilder().build(new StringReader("BEGIN:VCALENDAR\n" +
                "BEGIN:VEVENT\n" +
                "DTSTAMP:20181024T153406Z\n" +
                "RRULE:FREQ=MONTHLY;INTERVAL=1;BYMONTHDAY=1\n" +
                "DTSTART;VALUE=DATE:20180101\n" +
                "DTEND;VALUE=DATE:20391231\n" +
                "END:VEVENT\n" +
                "END:VCALENDAR\n"));
        System.out.printf("monthly " + monthly);
    }
}
`

**Comment by mytechtoday** [comment]
Seems like its the cache issue with our application. 
Closing it as its nor related to java 11.
