### ISSUE TITLE
Memory leak occurred (in StrictMode)

### ISSUE THREAD

**Issue by allsoft777** [ical4j/ical4j#32]
Hello. I'm a software engineer developing an android application.
First above all, i'd like to say "thank you" for your support.
I've developed all of things related with the ical4j module.

But, i got an issue for memory leak when composing an event.
It was occurred in TimeZoneRegistryFactory.
I guess the stream is leaked..because the thread is un-safe.

Is there any workaround for this?
(i.e options..)

Thanks.

05-12 10:48:08.808      952-967/com.android.calendar E/StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'end' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
            at java.util.zip.Inflater.<init>(Inflater.java:82)
            at java.util.zip.ZipFile.getInputStream(ZipFile.java:331)
            at java.util.jar.JarFile.getInputStream(JarFile.java:390)
            at libcore.net.url.JarURLConnectionImpl.getInputStream(JarURLConnectionImpl.java:222)
            at java.net.URL.openStream(URL.java:470)
            at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:444)
            at net.fortuna.ical4j.util.ResourceLoader.getResourceAsStream(ResourceLoader.java:77)
            at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<clinit>(TimeZoneRegistryImpl.java:76)
            at net.fortuna.ical4j.model.DefaultTimeZoneRegistryFactory.createRegistry(DefaultTimeZoneRegistryFactory.java:48)
            at com.android.calendar.icalendar.encoder.BaseEventEncoder.addDateTimeProperty(BaseEventEncoder.java:169)

**Comment by benfortuna** [comment]
Thanks for the feedback. I think I have a fix for the issue in this pull request:

https://github.com/ical4j/ical4j/pull/33

I'll try to get it merged and deployed in a new release shortly.

**Comment by benfortuna** [comment]
Closing issue as fixed. Feel free to reopen if problem still manifests.
