### ISSUE TITLE
ICal XPropterty with date and timezone causes Parser Excetpion Invalid parameter: TZID

### ISSUE THREAD

**Issue by pussbb** [ical4j/ical4j#339]
**Describe the bug**
Parsing ICAL fails with custom ICAL property which contains date and timezone fails with 'Invalid parametr TZID'
for e.g. 
`X-LOTUS-LASTALL-RDATES;TZID=India Standard Time:20170505T160000`
will cuase 
`net.fortuna.ical4j.data.ParserException: Error at line 80:Invalid parameter: TZID`

**To Reproduce**
```java
import net.fortuna.ical4j.data.CalendarBuilder;
import net.fortuna.ical4j.data.ParserException;
import net.fortuna.ical4j.util.CompatibilityHints;

import java.io.IOException;
import java.io.StringReader;

public class Test {

    public static void main(String[] args) throws IOException, ParserException {
        final String ical = "BEGIN:VCALENDAR\n" +
                "CALSCALE:GREGORIAN\n" +
                "PRODID:-//Lotus Development Corporation//NONSGML Notes 9.0.1//EN_S\n" +
                "VERSION:2.0\n" +
                "METHOD:REQUEST\n" +
                "X-LOTUS-CHARSET:UTF-8\n" +
                "BEGIN:VTIMEZONE\n" +
                "TZID:India Standard Time\n" +
                "BEGIN:STANDARD\n" +
                "DTSTART:19500101T020000\n" +
                "TZOFFSETFROM:+0530\n" +
                "TZOFFSETTO:+0530\n" +
                "END:STANDARD\n" +
                "END:VTIMEZONE\n" +
                "BEGIN:VEVENT\n" +
                "UID:FBE0A6D756CF5CE065258114004312AE-Lotus_Notes_Generated\n" +
                "RECURRENCE-ID:20170504T103000Z\n" +
                "LAST-MODIFIED:20170504T062410Z\n" +
                "DTSTAMP:20170504T062410Z\n" +
                "DTSTART;TZID=India Standard Time:20170504T160000\n" +
                "DTEND;TZID=India Standard Time:20170504T163000\n" +
                "X-MICROSOFT-CDO-OWNERAPPTID:17186\n" +
                "X-MICROSOFT-CDO-ALLDAYEVENT:FALSE\n" +
                "X-MICROSOFT-CDO-IMPORTANCE:1\n" +
                "PRIORITY:5\n" +
                "TRANSP:OPAQUE\n" +
                "X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE\n" +
                "SEQUENCE:0\n" +
                "SUMMARY:XXXXXXXXXXXXXXXX\n" +
                "X-SCALIX-LABEL:0\n" +
                "CLASS:PUBLIC\n" +
                "ATTENDEE;PARTSTAT=ACCEPTED;X-REPLYTIME=20170504T062410Z;CN=XXXXXXX\n" +
                " V/CHN/TCS:mailto:XXXXX@XXX,com\n" +
                "X-LOTUS-RECURID;RANGE=THISANDFUTURE:20170504T103000Z\n" +
                "X-LOTUS-LASTALL-RDATES;TZID=India Standard Time:20170504T160000\n" +
                "X-LOTUS-LASTALL-RDATES;TZID=India Standard Time:20170505T160000\n" +
                "X-LOTUS-CHANGE-INST-DATES:20170504T103000Z\n" +
                "X-LOTUS-CHANGE-INST-DATES:20170505T103000Z\n" +
                "X-LOTUS-INITIAL-RDATES:20170504T103000Z\n" +
                "X-LOTUS-INITIAL-RDATES:20170505T103000Z\n" +
                "X-LOTUS-BROADCAST:FALSE\n" +
                "X-LOTUS-UPDATE-SEQ:2\n" +
                "X-LOTUS-UPDATE-WISL:$W:1;$O:1;$M:1;RequiredAttendees:1;INetRequiredNames:\n" +
                " 1;AltRequiredNames:1;StorageRequiredNames:1;OptionalAttendees:1;\n" +
                " INetOptionalNames:1;AltOptionalNames:1;StorageOptionalNames:1;ApptUNIDURL:\n" +
                " 1;STUnyteConferenceURL:1;STUnyteConferenceID:1;SametimeType:1;\n" +
                " WhiteBoardContent:1;STRoomName:1;$S:2;$B:2;$L:2;$E:2;$R:2\n" +
                "X-LOTUS-NOTESVERSION:2\n" +
                "X-LOTUS-NOTICETYPE:I\n" +
                "X-LOTUS-APPTTYPE:3\n" +
                "X-LOTUS-CHILD-UID:DD8B93017528A8CB65258114004312C2\n" +
                "ATTACH:CID:0015d2b34ae531dd.1@OOOXODOODODOD\n" +
                "END:VEVENT\n" +
                "END:VCALENDAR";

        System.setProperty("ical4j.parsing.relaxed", "true");
        System.setProperty("ical4j.validation.relaxed", "true");
        System.setProperty("ical4j.compatibility.outlook", "true");
        System.setProperty("ical4j.compatibility.notes", "true");
        System.setProperty("ical4j.unfolding.relaxed", "true");
        System.setProperty("net.fortuna.ical4j.timezone.update.enabled", "true");
        System.setProperty("net.fortuna.ical4j.timezone.date.floating", "true");
        System.setProperty("net.fortuna.ical4j.timezone.cache.impl", "net.fortuna.ical4j.util.MapTimeZoneCache");

        CompatibilityHints.setHintEnabled(CompatibilityHints.KEY_RELAXED_PARSING, true);
        CompatibilityHints.setHintEnabled(CompatibilityHints.KEY_RELAXED_VALIDATION, true);
        CompatibilityHints.setHintEnabled(CompatibilityHints.KEY_RELAXED_UNFOLDING, true);
        CompatibilityHints.setHintEnabled(CompatibilityHints.KEY_OUTLOOK_COMPATIBILITY, true);
        CompatibilityHints.setHintEnabled(CompatibilityHints.KEY_NOTES_COMPATIBILITY, true);

        (new CalendarBuilder()).build(new StringReader(ical));
    }
}

```

```shell
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" net.fortuna.ical4j.data.ParserException: Error at line 54:Invalid parameter: TZID
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:158)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:183)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:171)
	at Test.main(Test.java:81)
Caused by: net.fortuna.ical4j.model.CalendarException: Invalid parameter: TZID
	at net.fortuna.ical4j.data.DefaultContentHandler.resolveTimezones(DefaultContentHandler.java:201)
	at net.fortuna.ical4j.data.DefaultContentHandler.endCalendar(DefaultContentHandler.java:67)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:127)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:180)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:149)
	... 3 more
```

**Expected behavior**
Not sure but maybe do not apply timezone for XProperty or try to apply timezone to date and if fails print an waring or ignore since XProperty its custom property and client who created it should/must apply or not timezone to datetime value.

**Environment (please complete the following information):**
 - OS:  Linux
 - Java Version  1.8
- Ical4j version 3.0.7

**Comment by staleks** [comment]
I've encountered same issue.

+1

**Comment by marcoismobile** [comment]
Having the same problem over here with the following property:

`X-LOTUS-START;TZID="Western/Central Europe":20190910T103000`

Seems like updating the _net.fortuna.ical4j.data.DefaultContentHandler_ class with the following code will fix this problem.

```
            // If timezone found, then update date property
            if (timezone != null) {
                for (Property property : properties) {

                    // Don't set timezones on XProperties
                    if (property instanceof XProperty) {
                        continue;
                    }

                    if (tzParam.equals(property.getParameter(Parameter.TZID))) {
```

**Comment by marcoismobile** [comment]
@benfortuna can you shed some light on this problem?

Are you aware of a workaround or solution for this problem? Because on this moment it is impossible to parse icalendar objects with XProperties containing TZID (like X-LOTUS-START).

Thanks in advance!

**Comment by pussbb** [comment]
@marcoismobile 
as for workaround I remove TZID from custom property with 
 following req expr. 
```java
Pattern.compile("X-(.*);TZID=.*:(.*)").matcher(icalStr).replaceAll("X-$1:$2")
```
Not sure if its right way but I do not need custom X- propreties, relay on standart ical rfc .

Demo
```shell
:~$ jshell
|  Welcome to JShell -- Version 11.0.4
|  For an introduction type: /help intro

jshell> var pat = Pattern.compile("X-(.*);TZID=.*:(.*)");
pat ==> X-(.*);TZID=.*:(.*)

jshell> pat.matcher("X-LOTUS-LASTALL-RDATES;TZID=India Standard Time:20170505T160000").replaceAll("X-$1:$2")
$2 ==> "X-LOTUS-LASTALL-RDATES:20170505T160000"

jshell> 
```
