### ISSUE TITLE
Invalid Time Zone ID

### ISSUE THREAD

**Issue by jamieb22** [ical4j/ical4j#367]
**Describe the bug**

ICal4J cannot parse the below Event from Office 365, despite the fact the ical4j parser is put in relaxed mode. It seems there are some strange chars prefixed to Time Zone ID.

```
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:
BEGIN:STANDARD
DTSTART:16010101T000000
TZOFFSETFROM:+0000
TZOFFSETTO:+0000
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T000000
TZOFFSETFROM:+0000
TZOFFSETTO:+0000
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ORGANIZER;CN=Bruce Roberts:MAILTO:roberts@company.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=Bruce Robe
 rts:MAILTO:roberts@company.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=Sam Peter
 :MAILTO:sam@company.com
ATTACH:CID:DFAA0447B2C90349A5BFD7B90216B66D@eurprd05.prod.outlook.com
DESCRIPTION;LANGUAGE=en-ZA:This event has been changed
UID:t21ocubdt9jagerldbkak7uhcg@google.com
SUMMARY;LANGUAGE=en-ZA:Updated Invitation: Sam at Sillick @ Wed Aug 26\, 2
 015 11:00 - 12:00 (sam@company.com)
DTSTART;TZID=:20150826T090000
DTEND;TZID=:20150826T100000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20150825T093708Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:1
LOCATION;LANGUAGE=en-ZA:17 Commerce Crescent\,Eastgate
X-MICROSOFT-CDO-APPT-SEQUENCE:1
X-MICROSOFT-CDO-OWNERAPPTID:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MICROSOFT-LOCATIONS:[{"DisplayName":"31 Ace Crescent\,Westgate"\,"Lo
 cationAnnotation":""\,"LocationUri":""\,"LocationStreet":""\,"LocationCity
 ":""\,"LocationState":""\,"LocationCountry":""\,"LocationPostalCode":""\,"
 LocationFullAddress":""}]
END:VEVENT
END:VCALENDAR
```

**To Reproduce**

Try to parse the above calendar. An Exception is thrown:

```
21:15:12.122 [main] DEBUG c.s.a.s.exception.ChainedException - 
net.fortuna.ical4j.data.ParserException: Error at line 52:Invalid TimeZone ID: []
	at com.stimulus.util.ical4j.RelaxedCalendarParserImpl.parse(RelaxedCalendarParserImpl.java:159)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:183)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:171)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:158)
	...
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at 
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.stimulus.archiva.mock.ApplicationMockRule$1.evaluate(ApplicationMockRule.java:69)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalArgumentException: Invalid TimeZone ID: []
	at org.apache.commons.lang3.Validate.notBlank(Validate.java:451)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.getTimeZone(TimeZoneRegistryImpl.java:165)
	at net.fortuna.ical4j.data.DefaultContentHandler.resolveTimezones(DefaultContentHandler.java:184)
	at net.fortuna.ical4j.data.DefaultContentHandler.endCalendar(DefaultContentHandler.java:67)
```
	
**Expected behavior**

If relaxed parsing is enabled, iCal4j should continue to parse the calendar.

**Environment (please complete the following information):**
 Java 8, Mac OS X

**Comment by edwhiting** [comment]
The RFC 5545 specification says at section 3.2.19 that the value of timezone id in a DTSTART;TZID field or a DTEND;TZID field must match the TZID field for the matching timezone definition.  The above example looks valid because the timezone id is the same in all three fields, that is, it is blank.
https://icalendar.org/iCalendar-RFC-5545/3-2-19-time-zone-identifier.html

The above example validates ok at the [iCalendar validator](https://icalendar.org/validator.html).

**Comment by edwhiting** [comment]
@benfortuna I propose moving or removing the following code in `TimeZoneRegistryImpl.getTimeZone`:
```java
Validate.notBlank(id, "Invalid TimeZone ID: [%s]", id);
```
During parsing the blank timezone does get loaded into the timezones map in `TimeZoneRegistryImpl`, and it can be fetched by its id (a blank string) in the `getTimeZone` method, so having the the validation step at the start of that method is probably incorrect for this use case.  A variant solution might be to insert the validation statement immediately after the first null check on the timezone object in that method instead.  What do you think?

I tested my proposed changes using the above .ics file as a basis for the test data but with the `X-MICROSOFT-*` and `SUMMARY;LANGUAGE` fields removed for brevity and compatibility with strict mode.  I used test case 'verify parsing of calendar file' in `CalendarParserImplSpec` and the whole the test suite passed.  I have pushed a branch [edwhiting/issue-367](https://github.com/ical4j/ical4j/compare/develop...edwhiting:edwhiting/issue-367?expand=1) to my repo if you want to take a look.
