### ISSUE TITLE
NPE in TimeZoneRegistryImpl.java (Thread.currentThread().getContextClassLoader() )

### ISSUE THREAD

**Issue by prsvic** [ical4j/ical4j#369]
NPE when getting contextClassLoader in application deployed on Tomcat 7.

```
java.lang.ExceptionInInitializerError: null
	at net.fortuna.ical4j.model.DefaultTimeZoneRegistryFactory.createRegistry(DefaultTimeZoneRegistryFactory.java:48) ~[ical4j-3.0.1.jar:na]
	at net.fortuna.ical4j.data.CalendarBuilder.<init>(CalendarBuilder.java:105) ~[ical4j-3.0.1.jar:na]
	...
Caused by: java.lang.NullPointerException: null
	at net.fortuna.ical4j.util.ResourceLoader.getResourceAsStream(ResourceLoader.java:79) ~[ical4j-3.0.1.jar:na]
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<clinit>(TimeZoneRegistryImpl.java:74) ~[na:na]
```

Maybe you could add the same null check as in #71 ?

**Comment by rfc2822** [comment]
Have you set the thread's contextClassLoader?

**Comment by prsvic** [comment]
I'm not setting anything - it's Tomcat's domain in this case

**Comment by rfc2822** [comment]
Guess you have to set the current thread's contextClassLoader (or configure Tomcat to do so).

**Comment by benfortuna** [comment]
I'll add the null check because the library should never throw a NullPtrException. 

However as suggested by @rfc2822 you may need to find out why the ContextClassLoader is null because I think the fallback method to lookup resources won't work in Tomcat.
