### ISSUE TITLE
Unsupported parameter name: DELEGATED-TO

### ISSUE THREAD

**Issue by kunlk** [ical4j/ical4j#375]
I use ical4j to parse an ics string, but got this error: Unsupported parameter name: DELEGATED-TO

net.fortuna.ical4j.data.ParserException: Error at line 22:Unsupported parameter name: DELEGATED-TO
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:158) ~[ical4j-3.0.9.jar:?]
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:183) ~[ical4j-3.0.9.jar:?]
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:171) ~[ical4j-3.0.9.jar:?]

Here are the part of the ics string:

ATTENDEE;PARTSTAT=DECLINED;CN="atlas test01/ABC"
 ;DELEGATED-FROM="mailto:atlas_test02/ABC@abc.com"
 ;RSVP=TRUE:mailto:fakeinternet821address@mailto.com
ATTENDEE;PARTSTAT=DELEGATED;DELEGATED-TO="mailto:ticket1887@youtrack.com";RSVP=FALSE
 :mailto:atlas_test02/ABC@abc.com

It looks like the DELEGATED-FROM can be parsed, but failed at DELEGATED-TO.

**Comment by benfortuna** [comment]
PR merged.
