### ISSUE TITLE
Missing expected token, last token: ERROR: No Value

### ISSUE THREAD

**Issue by kinoegit** [ical4j/ical4j#381]
**Describe the bug**
Creating a new entry in KDE Plasma/ KOrganizer causes error when synced with the phone

**To Reproduce**
1. Create a new entry in KDE Plasma/ KOrganizer
2. syncronize with smartphone
3. syncronize Davx5 on the smartphone
-> 'at.bitfire.ical4android.InvalidCalendarException: Couldn't parse iCalendar' 
and 
-> 'net.fortuna.ical4j.data.ParserException: Error at line 26:Missing expected token, last token: ERROR: No Value'

**Expected behavior**
Syncronization of PC and Smartphone

**Debug info**
```
EXCEPTION:
at.bitfire.ical4android.InvalidCalendarException: Couldn't parse iCalendar
	at at.bitfire.ical4android.ICalendar$Companion.fromReader(ICalendar.kt:72)
	at at.bitfire.ical4android.Event$Companion.eventsFromReader(Event.kt:76)
	at at.bitfire.ical4android.Event$Companion.eventsFromReader$default(Event.kt:75)
	at at.bitfire.davdroid.syncadapter.CalendarSyncManager.processVEvent(CalendarSyncManager.kt:160)
	at at.bitfire.davdroid.syncadapter.CalendarSyncManager.access$processVEvent(CalendarSyncManager.kt:42)
	at at.bitfire.davdroid.syncadapter.CalendarSyncManager$downloadRemote$1$1.invoke(CalendarSyncManager.kt:124)
	at at.bitfire.davdroid.syncadapter.CalendarSyncManager$downloadRemote$1$1.invoke(CalendarSyncManager.kt:42)
	at at.bitfire.dav4jvm.DavResource.get(DavResource.kt:211)
	at at.bitfire.davdroid.syncadapter.CalendarSyncManager$downloadRemote$1.invoke(CalendarSyncManager.kt:118)
	at at.bitfire.davdroid.syncadapter.CalendarSyncManager$downloadRemote$1.invoke(CalendarSyncManager.kt:42)
	at at.bitfire.davdroid.syncadapter.SyncManager.useRemote(SyncManager.kt:812)
	at at.bitfire.davdroid.syncadapter.CalendarSyncManager.downloadRemote(CalendarSyncManager.kt:117)
	at at.bitfire.davdroid.syncadapter.SyncManager$syncRemote$1$1.run(SyncManager.kt:454)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: net.fortuna.ical4j.data.ParserException: Error at line 26:Missing expected token, last token: ERROR: No Value
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:158)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:198)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:178)
	at at.bitfire.ical4android.ICalendar$Companion.fromReader(ICalendar.kt:70)
	... 17 more
Caused by: java.lang.IllegalArgumentException: Missing expected token, last token: ERROR: No Value
	at net.fortuna.ical4j.model.Recur.nextToken(Recur.java:247)
	at net.fortuna.ical4j.model.Recur.<init>(Recur.java:233)
	at net.fortuna.ical4j.model.property.RRule.setValue(RRule.java:113)
	at net.fortuna.ical4j.data.CalendarBuilder$ContentHandlerImpl.propertyValue(CalendarBuilder.java:299)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(CalendarParserImpl.java:282)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.access$1100(CalendarParserImpl.java:229)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:210)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:422)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$900(CalendarParserImpl.java:406)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:208)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:422)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$900(CalendarParserImpl.java:406)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:208)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:115)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:180)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:149)
	... 20 more
```

**Specifications:**
 - Operating System: Arch Linux 
*KDE Plasma Version: 5.17.4
*KDE Frameworks Version: 5.65.0
*Java environment /runtime 3-2
*KOrganizer 19.12.0-1
*KCalendarcore 5.65.0-2
*Libical 3.0.7-1

 - Android 8.0.0 
*at.bitfire.davdroid 2.6.1.1-ose
*com.android.contacts 1.7.22
*net.cloudcal.cal 1.21.01c
*ws.xsoh.etar 1.0.19

**Comment by kinoegit** [comment]
Update to KDE Frameworks 5.66.0 > KCalendarCore: Fix RRULE generation for timezones fixed the issue

**Comment by benfortuna** [comment]
Closing issue, resolved in source calendar data.
