### ISSUE TITLE
RRule throws IllegalArgumentException instead of ParseException

### ISSUE THREAD

**Issue by pkubowicz** [ical4j/ical4j#411]
**Describe the bug**
The JavaDoc for RRule constructor says it throws ParseException.

It seems that in reality ParseException is never thrown. `RRule` class does not throw any exceptions on its own. `Recur` class throws only IAE, although its JavaDoc also say it throws ParseException.

**To Reproduce**
1. Call `new RRule("a b c")`

```
Exception in thread "main" java.lang.IllegalArgumentException: Missing expected token, last token: a b c
	at net.fortuna.ical4j.model.Recur.nextToken(Recur.java:271)
	at net.fortuna.ical4j.model.Recur.<init>(Recur.java:259)
	at net.fortuna.ical4j.model.property.RRule.setValue(RRule.java:115)
	at net.fortuna.ical4j.model.property.RRule.<init>(RRule.java:72)
```

**Expected behavior**
All places in `Recur` that `throw new IllegalArgumentException` should be replaced with `throw new ParseException`.

**Environment (please complete the following information):**
OpenJDK 11
ical4j 3.0.18

**Additional context**

**Comment by benfortuna** [comment]
Hi,

It will throw a `ParseException` if the `UNTIL` part of the recurrence string is an invalid date representation.

Runtime exceptions like `IllegalArgumentException` are not explicitly documented currently, although it probably should be in this case.

I'll update the documentation for now to reduce confusion.

**Comment by pkubowicz** [comment]
I want to be able to catch all exceptions coming from ical4j (and nothing more). From what you suggest I will have to do the following: `catch(IllegalArgumentException | ParseException e)`. This doesn't look good.

If you want to use unchecked exceptions, please create your own subclass of RuntimeException, so that I will know that an exception comes from ical4j for sure.

Do you really need ParseException? It's a checked exception, which makes it really awkward to use Java 8+ features like streams. Removing it from function signature will create a breaking change (code using ical4j will stop to compile `catch (ParseException e)`) but you can do it in version 4.

**Comment by benfortuna** [comment]
The coming ical4j v4 will fix a lot of these issues regarding use of java 8 streams, etc. 

I am trying to remove many of the checked exceptions, but probably won't do the same in ica4j 3.x due to breaking compatibility.

**Comment by hegdevenky** [comment]
Hello @benfortuna 
I'm using constructor of `RRule` / `Recur`  to validate the recurrence rule without enabling relaxed mode. I see if the RECUR has duplicate properties ex - `FREQ=WEEKLY;BYDAY=SU,MO,WE;BYHOUR=10;BYMINUTE=30`  it overwrite value is this expected behavior?
