### ISSUE TITLE
Timezone registry empty - Our unit tests fail ical4j tests after Nov. 17th sometime.

### ISSUE THREAD

**Issue by bjornharvold** [ical4j/ical4j#464]
**Describe the bug**
Between our latest production release (Nov. 17th) and now, TimezoneRegistry stopped working and our ical4j tests suddenly failed. The reason is there are no timezones registered with the registry.

**To Reproduce**

TimeZoneRegistry registry = TimeZoneRegistryFactory.getInstance().createRegistry();
TimeZone timezone = this.registry.getTimeZone("Asia/Bangkok");

System.out.println(timezone); // is null

**Expected behavior**
Actual Timezone should return 

**Screenshots**
<img width="833" alt="Screen Shot 2020-11-23 at 7 11 44 PM" src="https://user-images.githubusercontent.com/641791/99960695-c0b4a600-2dbf-11eb-9513-e9ee2a778a0c.png">

**Environment (please complete the following information):**
 - OS: Mac OS Big Sur
 - Java Version: 8 Java AdoptOpenJDK 1.8.0_275

**Additional context**
Only configuration property we have used all this time is:
net.fortuna.ical4j.timezone.cache.impl=net.fortuna.ical4j.util.MapTimeZoneCache

Upgraded from 3.0.5 to 3.0.20 today to see if that changed anything. No. The issue is not version dependent.

**Comment by n-n-nebbl** [comment]
Looks like the same issue i have in https://github.com/ical4j/ical4j/issues/463

**Comment by ShaneMcGowan** [comment]
Same issue here, breaking our ical email sending.
Only noticed this morning but could have been happening over the weekend

`[WARN] Error occurred loading VTimeZone
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at net.fortuna.ical4j.model.TimeZoneLoader.updateDefinition(TimeZoneLoader.java:146)
	at net.fortuna.ical4j.model.TimeZoneLoader.loadVTimeZone(TimeZoneLoader.java:109)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.getTimeZone(TimeZoneRegistryImpl.java:181)`

**Comment by benfortuna** [comment]
Apologies, we just had an outage on the timezone update server and I had to rebuild it. 

Hopefully it should be restored now, but if you see any further errors or have feedback on improvements pls add comments to this ticket.

**Comment by ShaneMcGowan** [comment]
> Apologies, we just had an outage on the timezone update server and I had to rebuild it.
> 
> Hopefully it should be restored now, but if you see any further errors or have feedback on improvements pls add comments to this ticket.

Everything back working on our end, thanks for the quick response!

Would you be able to provide me with a link to any info on how to host your own registry in future? I've looked here https://ical4j.github.io/ical4j-user-guide/timezones/ but not much info on self hosted.

**Comment by benfortuna** [comment]
Sure I will try to add some documentation to tzurl project for self-hosted registry. It's not too complicated, basically a static site with some rewrite rules, could be done with apache or nginx, etc.

Here is the current build branch used to generate the zoneinfo files (haven't yet merged back to master):

https://github.com/benfortuna/tzurl/tree/feature/make-rearguard

**Comment by bjornharvold** [comment]
Thanks guys!
