### ISSUE TITLE
Exception Initializer

### ISSUE THREAD

**Issue by raghunandankavi2010** [ical4j/ical4j#524]
```
 Process: com.peoplemesh.now, PID: 11567
    java.lang.ExceptionInInitializerError
        at net.fortuna.ical4j.util.Configurator.getProperty(Configurator.java:75)
        at net.fortuna.ical4j.data.CalendarParserFactory.<clinit>(CalendarParserFactory.java:63)
        at net.fortuna.ical4j.data.CalendarParserFactory.getInstance(CalendarParserFactory.java:75)
        at net.fortuna.ical4j.data.CalendarBuilder.<init>(CalendarBuilder.java:122)
        at com.peoplemesh.now.ui.mylist.oneonone.timeline.OneOnOneTimeLineFragment.parseCalendar(OneOnOneTimeLineFragment.kt:697)
        at com.peoplemesh.now.ui.mylist.oneonone.timeline.OneOnOneTimeLineFragment$onViewCreated$11$1.invokeSuspend(OneOnOneTimeLineFragment.kt:592)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:266)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at com.peoplemesh.now.ui.mylist.oneonone.timeline.OneOnOneTimeLineFragment.onViewCreated$lambda-20(OneOnOneTimeLineFragment.kt:591)
        at com.peoplemesh.now.ui.mylist.oneonone.timeline.OneOnOneTimeLineFragment.h(Unknown Source:0)
        at d0.h.onChanged(Unknown Source:4)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: org.apache.commons.logging.LogConfigurationException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference (Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference)
        at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:571)
        at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:292)
        at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:269)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
        at net.fortuna.ical4j.util.Configurator.<clinit>(Configurator.java:51)
        at net.fortuna.ical4j.util.Configurator.getProperty(Configurator.java:75) 
        at net.fortuna.ical4j.data.CalendarParserFactory.<clinit>(CalendarParserFactory.java:63) 
        at net.fortuna.ical4j.data.CalendarParserFactory.getInstance(CalendarParserFactory.java:75) 
        at net.fortuna.ical4j.data.CalendarBuilder.<init>(CalendarBuilder.java:122) 
        at com.peoplemesh.now.ui.mylist.oneonone.timeline.OneOnOneTimeLineFragment.parseCalendar(OneOnOneTimeLineFragment.kt:697) 
        at com.peoplemesh.now.ui.mylist.oneonone.timeline.OneOnOneTimeLineFragment$onViewCreated$11$1.invokeSuspend(OneOnOneTimeLineFragment.kt:592) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:266) 
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30) 
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25) 
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110) 
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) 
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) 
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1) 
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47) 
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1) 
        at com.peoplemesh.now.ui.mylist.oneonone.timeline.OneOnOneTimeLineFragment.onViewCreated$lambda-20(OneOnOneTimeLineFragment.kt:591) 
        at com.peoplemesh.now.ui.mylist.oneonone.timeline.OneOnOneTimeLineFragment.h(Unknown Source:0) 
        at d0.h.onChanged(Unknown Source:4) 
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133) 
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151) 
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309) 
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50) 
        at androidx.lifecycle.LiveData$1.run(LiveData.java:93) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
        at org.apache.commons.logging.impl.LogFactoryImpl.createLogFromClass(LogFactoryImpl.java:1067)
        at org.apache.commons.logging.impl.LogFactoryImpl.discoverLogImplementation(LogFactoryImpl.java:844)
        at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:541)
        at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:292) 
        at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:269) 
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655) 
        at net.fortuna.ical4j.util.Configurator.<clinit>(Configurator.java:51) 
        at net.fortuna.ical4j.util.Configurator.getProperty(Configurator.java:75) 
        at net.fortuna.ical4j.data.CalendarParserFactory.<clinit>(CalendarParserFactory.java:63) 
        at net.fortuna.ical4j.data.CalendarParserFactory.getInstance(CalendarParserFactory.java:75) 
        at net.fortuna.ical4j.data.CalendarBuilder.<init>(CalendarBuilder.java:122) 
        at com.peoplemesh.now.ui.mylist.oneonone.timeline.OneOnOneTimeLineFragment.parseCalendar(OneOnOneTimeLineFragment.kt:697) 
        at com.peoplemesh.now.ui.mylist.oneonone.timeline.OneOnOneTimeLineFragment$onViewCreated$11$1.invokeSuspend(OneOnOneTimeLineFragment.kt:592) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:266) 
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30) 
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25) 
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110) 
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) 
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) 
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1) 
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47) 
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1) 
        at com.peoplemesh.now.ui.mylist.oneonone.timeline.OneOnOneTimeLineFragment.onViewCreated$lambda-20(OneOnOneTimeLineFragment.kt:591) 
        at com.peoplemesh.now.ui.mylist.oneonone.timeline.OneOnOneTimeLineFragment.h(Unknown Source:0) 
        at d0.h.onChanged(Unknown Source:4) 
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133) 
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151) 
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309) 
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50) 
        at androidx.lifecycle.LiveData$1.run(LiveData.java:93) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```
Using     implementation 'ical4j:ical4j:0.9.20''

On android 11

Crash pointing to    
    
     val cb = CalendarBuilder()

**Comment by raghunandankavi2010** [comment]
This happens with obfuscation proguard enabled. What are the progurard rules for ical4j?

**Comment by benfortuna** [comment]
There is some proguard guidance in the user guide (from the old wiki), but I'm not sure if it is up to date. It may provide a basis for your testing though:

https://ical4j.github.io/ical4j-user-guide/android/#reducing-android-footprint-by-using-proguard

**Comment by raghunandankavi2010** [comment]
Thanks. I updated to latest lib and also you need ical4j.properties files in resource folder. Would be better if this is added to the documentation. Now it works with proguard as well.
