### ISSUE TITLE
ParserException: Error at line 13:Unable to obtain LocalDateTime from TemporalAccessor: 2020-01-01 of type java.time.LocalDate

### ISSUE THREAD

**Issue by svieujot** [ical4j/ical4j#527]
With version 4.0.0-alpha10:

The following file can not be parsed:
```
BEGIN:VCALENDAR
CALSCALE:GREGORIAN
PRODID:-//Ximian//NONSGML Evolution Calendar//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Arabian Standard Time
BEGIN:STANDARD
DTSTART;VALUE=DATE:20200101
TZNAME:Arabian Standard Time
TZOFFSETFROM:+0400
TZOFFSETTO:+0400
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTEND;TZID=Arabian Standard Time:20210331T150000
DTSTAMP:20210318T111652Z
DTSTART;TZID=Arabian Standard Time:20210331T140000
SEQUENCE:0
SUMMARY:Webinar - Middle East M&A: How new tax rules impact M&A deals
UID:421182d9-2d9c-4659-9b7d-d2b17b4c57e0
X-ALT-DESC;FMTTYPE=text/html:Click here to join the webnar:<br /><a
href="https://attendee.gotowebinar.com/register/XXX">https:
//attendee.gotowebinar.com/register/XXX</a>
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
CREATED:20210323T063157Z
LAST-MODIFIED:20210323T063157Z
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-P1D
X-EVOLUTION-ALARM-UID:347dd5204e415156dc40b475527f32147bf5937e
END:VALARM
END:VEVENT
END:VCALENDAR
```

and generates the following stack trace:
```
net.fortuna.ical4j.data.ParserException: Error at line 13:Unable to obtain LocalDateTime from TemporalAccessor: 2020-01-01 of type java.time.LocalDate
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:157)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:197)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:185)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:172)
	at com.seanergie.webdav.caldav.report.CalendarQueryReport.parseEvent(CalendarQueryReport.java:210)
        ...
```

**Comment by benfortuna** [comment]
Thanks for taking the time to test with ical4j 4-alpha. I've just run a test with this sample and can confirm there is an issue in the timezone `Observance` class.

I had made an assumption that `VTIMEZONE` definitions use `DATE-TIME` instances, however in this example the type is `DATE`:

```
DTSTART;VALUE=DATE:20200101
```

I will review the implementation and provide a fix shortly.

**Comment by svieujot** [comment]
Thank you !
