### ISSUE TITLE
NullPointerException in v 4.0.0-aplha10

### ISSUE THREAD

**Issue by svieujot** [ical4j/ical4j#531]
With the following vcalendar:

```
BEGIN:VCALENDAR
CALSCALE:GREGORIAN
PRODID:-//Ximian//NONSGML Evolution Calendar//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Asia/Dubai
X-LIC-LOCATION:Asia/Dubai
END:VTIMEZONE
BEGIN:VEVENT
UID:f8c1c9bb21ca95268ec7921a6c3d162c469287dd
DTSTAMP:20201112T111312Z
TRANSP:OPAQUE
DTSTART;TZID=Asia/Dubai:20201123T100000
DTEND;TZID=Asia/Dubai:20201123T103000
SUMMARY:10am - Hasan coming
CLASS:PUBLIC
CREATED:20201122T103805Z
LAST-MODIFIED:20201122T103805Z
END:VEVENT
END:VCALENDAR
```

The stack trace is:
```
net.fortuna.ical4j.data.ParserException: Error at line 8:Cannot invoke "net.fortuna.ical4j.model.component.Observance.getProperties()" because "current" is null
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:157)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:197)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:185)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:172)
	at com.seanergie.webdav.caldav.report.CalendarQueryReport.parseEvent(CalendarQueryReport.java:210)

....

java.lang.NullPointerException: Cannot invoke "net.fortuna.ical4j.model.component.Observance.getProperties()" because "current" is null
	at net.fortuna.ical4j.model.ZoneRulesBuilder.build(ZoneRulesBuilder.java:86)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.register(TimeZoneRegistryImpl.java:151)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.register(TimeZoneRegistryImpl.java:129)
	at net.fortuna.ical4j.data.DefaultContentHandler.endComponent(DefaultContentHandler.java:124)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:438)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$900(CalendarParserImpl.java:393)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:207)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:116)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:178)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:151)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:197)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:185)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:172)
	at com.seanergie.webdav.caldav.report.CalendarQueryReport.parseEvent(CalendarQueryReport.java:210)
```

**Comment by cketti** [comment]
We're encountering this in DAVx5 as well. See https://github.com/bitfireAT/davx5-ose/issues/2248

This is caused by a `VTIMEZONE` component that is missing both a `STANDARD` and a `DAYLIGHT` sub-component. Such `VTIMEZONE` components are invalid. But it would be nice if they were simply ignored.

ical4j 3.x did not throw an exception.

```java
@Test
public void VTIMEZONE_missing_standard_and_daylight() throws ParserException, IOException {
    Reader reader = new StringReader(
        "BEGIN:VCALENDAR\n" +
        "VERSION:2.0\n" +
        "PRODID:-//Example Corp.//CalDAV Client//EN\n" +
        "BEGIN:VTIMEZONE\n" +
        "TZID:UTC\n" +
        "END:VTIMEZONE\n" +
        "BEGIN:VEVENT\n" +
        "DTSTAMP:20260529T095200Z\n" +
        "UID:bc295665-5b3b-11f1-9a52-d843aea66ff2\n" +
        "DTSTART;TZID=UTC:20260528T120000\n" +
        "END:VEVENT\n" +
        "END:VCALENDAR"
    );

    new CalendarBuilder().build(reader);
}
```

I'm not quite sure what the best way would be to avoid the exception. Maybe validating the `VTimeZone` in `DefaultContentHandler.endComponent()` and only calling `TimeZoneRegistry.register()` for instances that pass validation?

https://github.com/ical4j/ical4j/blob/6ffcfc4fcba174b566939a288dfbb7613c9e4e74/src/main/java/net/fortuna/ical4j/data/DefaultContentHandler.java#L127-L130

@benfortuna Do you have a preference for how this should be fixed? I'm happy to create a PR to fix this issue.
