### ISSUE TITLE
Cannot create an ics by setting Method and VAlarm

### ISSUE THREAD

**Issue by charcoast** [ical4j/ical4j#597]
**Describe the bug**
Cannot create an ics by setting Method.REQUEST and VAlarm.

Returns an exception that prevents the file from being generated:
`Exception in thread "main" java.lang.UnsupportedOperationException: VALARM validation included in VEVENT or VTODO method validator.
	at net.fortuna.ical4j.model.component.VAlarm.getValidator(VAlarm.java:263)
	at net.fortuna.ical4j.model.component.CalendarComponent.validate(CalendarComponent.java:89)
	at net.fortuna.ical4j.validate.CalendarValidatorImpl.validate(CalendarValidatorImpl.java:65)
	at net.fortuna.ical4j.validate.CalendarValidatorImpl.validate(CalendarValidatorImpl.java:16)
	at net.fortuna.ical4j.model.Calendar.validate(Calendar.java:234)
	at net.fortuna.ical4j.model.Calendar.validate(Calendar.java:225)
	at net.fortuna.ical4j.data.CalendarOutputter.output(CalendarOutputter.java:96)
	at net.fortuna.ical4j.data.CalendarOutputter.output(CalendarOutputter.java:83)
	at org.example.Main.main(Main.java:83)`

Creating an ics with just VAlarm or just Method, the problem doesn't occur.

**To Reproduce**
1. Create a calendar
2. Set a VAlarm
3. Set a Method

**Expected behavior**
Hope this didn't throw an exception

**Environment (please complete the following information):**
 - OS: ZorinOs - Linux
 - Java Version 8

**Additional context**
I need METHOD because the Outlook application doesn't recognize RSVP without it.

**Comment by charcoast** [comment]
I found a temporary but not very ideal solution to the problem.
```
CalendarOutputter outputter = new CalendarOutputter();
outputter.setValidating(false);
outputter.output(calendar, fout);

**Comment by benfortuna** [comment]
Note that VALARM objects must be nested inside VEVENT, VTODO, etc. You can't have VALARM objects at the top level of a Calendar.

Please check you are adding your VALARM to the applicable VEVENT.
