### ISSUE TITLE
java.text.ParseException: Unparseable date: "20221207T170935" in ical4j when specifying time zone Australia/Lord_Howe

### ISSUE THREAD

**Issue by SwatiSatrusalya** [ical4j/ical4j#616]
I am getting a parsing exception while I am trying the following code:
`import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import net.fortuna.ical4j.model.TimeZone;
import net.fortuna.ical4j.model.TimeZoneRegistry;
import net.fortuna.ical4j.model.TimeZoneRegistryFactory;
import net.fortuna.ical4j.model.property.DtStart;

public class Timezone {

    public static void main(String[] args) {
        
        
        TimeZoneRegistry registry = TimeZoneRegistryFactory.getInstance().createRegistry();
        TimeZone tz;
        LocalDateTime now = LocalDateTime.now();
        meeting.setDtStartLocal(now);
        final DateTimeFormatter ICS_DATE_FORMATTER =
                DateTimeFormatter.ofPattern("yyyyMMdd'T'HHmmss");
        
        //tz = registry.getTimeZone("Asia/Calcutta");
        tz = registry.getTimeZone("Australia/Lord_Howe");
        DtStart dtstart;
        try {
		dtstart = new DtStart(now.format(ICS_DATE_FORMATTER),tz);
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }    
    }
}`
java.text.ParseException: Unparseable date: "20221207T170935"
    at java.base/java.text.DateFormat.parse(DateFormat.java:395)
    at net.fortuna.ical4j.model.DateTime.setTime(DateTime.java:418)
    at net.fortuna.ical4j.model.DateTime.<init>(DateTime.java:325)
    at net.fortuna.ical4j.model.property.DateProperty.setValue(DateProperty.java:137)
    at net.fortuna.ical4j.model.property.DtStart.<init>(DtStart.java:146)
    at Timezone.main(Timezone.java:33)
	
I have used ical4j 3.0.19 jar and their dependency jar .

Its working for all the timezone except for the timezone "Australia/Lord_Howe".

I am expecting the Dtstart value as :

DTSTART;TZID=Australia/Lord_Howe:20221207T170935

**Comment by SwatiSatrusalya** [comment]
Its working for all the timezone except for the timezone "Australia/Lord_Howe".That too its only fails with summer time (DST) for timezone "Australia/Lord_Howe".

**Comment by SwatiSatrusalya** [comment]
Could be please help me on this .

**Comment by benfortuna** [comment]
I've been able to recreate the issue with `Australia/Lord_Howe` timezone, however I'm not sure yet how to fix it.

It seems that the Java SimpleDateFormat may have an issue with the timezone change from 11:00 -> 10:30, as it seems to work when I change the definition to 11:00 -> 10:00.

I'll keep investigating, but as of now I don't have a fix.

**Comment by SwatiSatrusalya** [comment]
thanks a lot for the response and replication of issue @benfortuna .Please let me know when fix are available.

**Comment by SwatiSatrusalya** [comment]
Hi @benfortuna ,Any update regarding fix for above issue.

**Comment by SwatiSatrusalya** [comment]
Hi @benfortuna ,Any update regarding fix for above issue.

**Comment by SwatiSatrusalya** [comment]
Hi @benfortuna ,Any update regarding fix for above issue.

**Comment by Vignesh1304** [comment]
@benfortuna
Hi Team, It would be helpful if you provide update on this ...

**Comment by benfortuna** [comment]
I still don't have a fix for this, but if it's urgent you may want to look at upgrading to ical4j 4.x, which doesn't rely on SimpleDateFormat, so shouldn't have this problem.
