### ISSUE TITLE
Unsupported parameter name: RECEIVED-SEQUENCE

### ISSUE THREAD

**Issue by sysmat** [ical4j/ical4j#633]
**Is your feature request related to a problem? Please describe.**

To support RECEIVED-SEQUENCE when using getResponseBodyAsCalendar at

```
at net.fortuna.ical4j.model.ParameterFactoryImpl.createParameter(ParameterFactoryImpl.java:83)
	at net.fortuna.ical4j.data.CalendarBuilder$ContentHandlerImpl.parameter(CalendarBuilder.java:273)
	at net.fortuna.ical4j.data.CalendarParserImpl$ParameterParser.parse(CalendarParserImpl.java:370)

```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Using SOGO

**Comment by sysmat** [comment]
- ical4j:4.0.0-beta7 support it, from caldav4j it comes ver 3

```xml
<dependency>
            <groupId>com.github.caldav4j</groupId>
            <artifactId>caldav4j</artifactId>
            <version>1.0.5</version>
            <exclusions>
                <exclusion>
                    <groupId>org.mnode.ical4j</groupId>
                    <artifactId>ical4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- we need it because we overwrite it from caldav4j it has ver 3 -->
        <dependency>
            <groupId>org.mnode.ical4j</groupId>
            <artifactId>ical4j</artifactId>
            <version>4.0.0-beta7</version>
        </dependency>
```
