### ISSUE TITLE
ServiceLoader Action$Factory

### ISSUE THREAD

**Issue by querdenker2k** [ical4j/ical4j#64]
I'm getting an error when i use it inside an OSGI environment. With an older version its running fine.
The error occurs when the runtime is running and when i deactivate and active a bundle (where ical4j is used inside). 
Stacktrace:

```
Caused by: java.util.ServiceConfigurationError: net.fortuna.ical4j.model.PropertyFactory: Provider net.fortuna.ical4j.model.property.Action$Factory not a subtype
        at java.util.ServiceLoader.fail(ServiceLoader.java:231)
        at java.util.ServiceLoader.access$300(ServiceLoader.java:181)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:369)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
        at net.fortuna.ical4j.model.AbstractContentFactory.getFactory(AbstractContentFactory.java:85)
        at net.fortuna.ical4j.model.PropertyFactoryImpl.createProperty(PropertyFactoryImpl.java:78)
```

**Comment by paphko** [comment]
I get the same error when I build the **org.openhab.io.caldav** bundle from the current master branch and deploy it to a 1.8.2 runtime:

```
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [quartz-all-2.1.7.jar:na]
Caused by: java.util.ServiceConfigurationError: net.fortuna.ical4j.model.PropertyFactory: Provider net.fortuna.ical4j.model.property.Action$Factory not a subtype
        at java.util.ServiceLoader.fail(ServiceLoader.java:239) ~[na:1.8.0]
        at java.util.ServiceLoader.access$300(ServiceLoader.java:185) ~[na:1.8.0]
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376) ~[na:1.8.0]
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[na:1.8.0]
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[na:1.8.0]
        at net.fortuna.ical4j.model.AbstractContentFactory.getFactory(AbstractContentFactory.java:85) ~[na:na]
        at net.fortuna.ical4j.model.PropertyFactoryImpl.createProperty(PropertyFactoryImpl.java:78) ~[na:na]
        at net.fortuna.ical4j.data.CalendarBuilder$ContentHandlerImpl.startProperty(CalendarBuilder.java:326) ~[na:na]
        at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(CalendarParserImpl.java:206) ~[na:na]
        at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.access$1100(CalendarParserImpl.java:190) ~[na:na]
        at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:173) ~[na:na]
        at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:122) ~[na:na]
        at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:198) ~[na:na]
        at org.openhab.io.caldav.internal.job.EventReloaderJob.loadEvents(EventReloaderJob.java:299) ~[na:na]
        at org.openhab.io.caldav.internal.job.EventReloaderJob.loadEvents(EventReloaderJob.java:279) ~[na:na]
        at org.openhab.io.caldav.internal.job.EventReloaderJob.execute(EventReloaderJob.java:111) ~[na:na]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) ~[quartz-all-2.1.7.jar:na]
        ... 1 common frames omitted
```

**Comment by benfortuna** [comment]
I'm currently testing a workaround to this issue, although ultimately I am now thinking using ServiceLoader may not have been the best decision. I will ultimately look for a solution that is more compatible with OSGi environments. Here is the pull request: #80

**Comment by paphko** [comment]
@benfortuna Thank you for investigating this issue. Do I have to re-build the ical4j lib from sources myself to get the fix or is there somewhere a jar already available with that fix?

**Comment by benfortuna** [comment]
Hi,

There is a pre-built jar available here:

https://oss.sonatype.org/content/repositories/snapshots/org/mnode/ical4j/ical4j/2.0.0-bugfix-serviceloader-osgi-SNAPSHOT/

If you could let me know if you have success with it that would be
appreciated.

Regards,
Ben

**Comment by paphko** [comment]
@benfortuna Thanks, it works again!

**Comment by benfortuna** [comment]
Fixed for now, but will probably look at replacing ServiceLoader in future
