### ISSUE TITLE
ParserException illegal property for ics-files having breaks in the description

### ISSUE THREAD

**Issue by christf** [ical4j/ical4j#65]
when running 
	FileInputStream fin = new FileInputStream(filename);
			CalendarBuilder builder = new CalendarBuilder();
			Calendar calendar = builder.build(fin);
I am getting the below exception with ical4j 2-beta1 and 1.0.7

Exception in thread "main" net.fortuna.ical4j.data.ParserException: Error at line 25:Illegal property [ SAALE)HBF\, GLEIS 8\N\N2)]
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:148)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:210)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:191)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:179)
	at com.penguineering.snuselpi.Weckzeitfinder.main(Weckzeitfinder.java:49)
Caused by: java.lang.IllegalArgumentException: Illegal property [ SAALE)HBF\, GLEIS 8\N\N2)]
	at net.fortuna.ical4j.model.PropertyFactoryImpl.createProperty(PropertyFactoryImpl.java:978)
	at net.fortuna.ical4j.data.CalendarBuilder$ContentHandlerImpl.startProperty(CalendarBuilder.java:346)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(CalendarParserImpl.java:211)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.access$1(CalendarParserImpl.java:200)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:178)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:390)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$1(CalendarParserImpl.java:376)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:175)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:125)
	... 4 more

this is the calendar entry:
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//dmfs.org//mimedir.icalendar//EN
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20150322T170300
DESCRIPTION:1)	IC 2239\n	Ab 17:03 Magdeburg Hbf\, Gleis 3\n	An 17:53 Halle(
 Saale)Hbf\, Gleis 8\n\n2)	ICE 1715\n	Ab 18:00 Halle(Saale)Hbf\, Gleis 3\n	
 An 19:09 Erfurt Hbf\n\n3)	ICE 1572\n	Ab 19:18 Erfurt Hbf\, Gleis 1\n	An 21
 :35 Frankfurt(Main)Süd\, Gleis 7\n\n4)	S 4\n-> Kronberg(Taunus)\n	Ab 21:4
 8 Frankfurt(Main)Süd\, Gleis 4\n	An 21:53 Frankfurt(M)Konstablerwache\, G
 leis 3\n\n5)	Fußweg 4 Minuten\n\n6)	U 6\n-> Praunheim Heerstraße\, Frank
 furt am Main\n	Ab 21:57 Konstablerwache\, Frankfurt am Main\n	An 22:10 Hau
 sener Weg\, Frankfurt am Main\n
SUMMARY:Fahrt von Magdeburg Hbf nach Hausener Weg\, Frankfurt am Main\; Ums
 tiege: 4x\; Dauer: 05:07
LOCATION:Magdeburg Hbf
TRANSP:OPAQUE
DTEND;TZID=Europe/Berlin:20150322T221000
LAST-MODIFIED:20150322T160358Z
DTSTAMP:20150322T160358Z
CREATED:20150322T160358Z
UID:08b5d9ea-7759-4804-916e-6b1ec6f7fbe5
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT15M
ACTION:DISPLAY
DESCRIPTION:Default Event Notification
X-WR-ALARMUID:92011d6e-04b6-420f-b8b9-df0f78ff47d9
END:VALARM
END:VEVENT
END:VCALENDAR

What can I do to parse those files?

**Comment by penguineer** [comment]
Following the stack trace, there is an instantiation of an `UnfoldingReader`, which in its description says: "By specifying the system property "ical4j.unfolding.relaxed=true" iCalendar files created with Mozilla Calendar/Sunbird may be correctly unfolded."

A workaround is actually the line `System.setProperty("ical4j.unfolding.relaxed", "true");` before using the parser.

**Comment by christf** [comment]
with that setting in place, more ics entries can be parsed. Should I close this?
