### ISSUE TITLE
Time of Event not correct with Events from Wordpress Events Manager

### ISSUE THREAD

**Issue by ArnyminerZ** [ical4j/ical4j#651]
**Describe the bug**
When using events provided from the [Wordpress' Events Manager](https://wordpress.org/plugins/events-manager/) plugin, start time is parsed incorrectly.

**To Reproduce**
1. Try parsing the following ical:

    ```icalendar
    BEGIN:VCALENDAR
    VERSION:2.0
    BEGIN:VEVENT
    UID:xxx@xxx.de
    DTSTART;TZID=Europe/Berlin:20230905T200000
    DTEND;TZID=Europe/Berlin:20230905T210000
    SUMMARY:xxxxxxxxxxxxxxxxxxx
    END:VEVENT
    BEGIN:VTIMEZONE
    TZID:Europe/Berlin
    BEGIN:DAYLIGHT
    DTSTART:20230326T030000
    TZOFFSETFROM:+0100
    TZOFFSETTO:+0200
    TZNAME:CEST
    END:DAYLIGHT
    BEGIN:STANDARD
    DTSTART:20231029T020000
    TZOFFSETFROM:+0200
    TZOFFSETTO:+0100
    TZNAME:CET
    END:STANDARD
    BEGIN:DAYLIGHT
    DTSTART:20240331T030000
    TZOFFSETFROM:+0100
    TZOFFSETTO:+0200
    TZNAME:CEST
    END:DAYLIGHT
    BEGIN:STANDARD
    DTSTART:20241027T020000
    TZOFFSETFROM:+0200
    TZOFFSETTO:+0100
    TZNAME:CET
    END:STANDARD
    END:VTIMEZONE
    END:VCALENDAR
    ```
2. Example test code:
    ```kotlin
    import net.fortuna.ical4j.data.CalendarBuilder
    import net.fortuna.ical4j.model.Component
    import net.fortuna.ical4j.model.component.VEvent
    import org.junit.Test
    import java.io.StringReader
    
    class WordpressEventsManagerTest {
        @Test
        fun test_parsing() {
            val calendar = CalendarBuilder().build(
                StringReader(
                    "BEGIN:VCALENDAR\n" +
                        "VERSION:2.0\n" +
                        "BEGIN:VEVENT\n" +
                        "UID:xxx@xxx.de\n" +
                        "DTSTART;TZID=Europe/Berlin:20230905T200000\n" +
                        "DTEND;TZID=Europe/Berlin:20230905T210000\n" +
                        "SUMMARY:xxxxxxxxxxxxxxxxxxx\n" +
                        "END:VEVENT\n" +
                        "BEGIN:VTIMEZONE\n" +
                        "TZID:Europe/Berlin\n" +
                        "BEGIN:DAYLIGHT\n" +
                        "DTSTART:20230326T030000\n" +
                        "TZOFFSETFROM:+0100\n" +
                        "TZOFFSETTO:+0200\n" +
                        "TZNAME:CEST\n" +
                        "END:DAYLIGHT\n" +
                        "BEGIN:STANDARD\n" +
                        "DTSTART:20231029T020000\n" +
                        "TZOFFSETFROM:+0200\n" +
                        "TZOFFSETTO:+0100\n" +
                        "TZNAME:CET\n" +
                        "END:STANDARD\n" +
                        "BEGIN:DAYLIGHT\n" +
                        "DTSTART:20240331T030000\n" +
                        "TZOFFSETFROM:+0100\n" +
                        "TZOFFSETTO:+0200\n" +
                        "TZNAME:CEST\n" +
                        "END:DAYLIGHT\n" +
                        "BEGIN:STANDARD\n" +
                        "DTSTART:20241027T020000\n" +
                        "TZOFFSETFROM:+0200\n" +
                        "TZOFFSETTO:+0100\n" +
                        "TZNAME:CET\n" +
                        "END:STANDARD\n" +
                        "END:VTIMEZONE\n" +
                        "END:VCALENDAR"
                )
            )
    
            val event = calendar.getComponent<VEvent>(Component.VEVENT)
            assert(event.startDate.value == "20230905T200000") {
                "Start date does not match. Expected: <20230905T200000>. Actual: <${event.startDate.value}>"
            }
        }
    }
    ```
3. Assertion fails with `Start date does not match. Expected: <20230905T200000>. Actual: <20230905T010000>`.

**Expected behavior**
DTSTART should be `20230905T200000` and not `20230905T010000`

**Environment (please complete the following information):**
 - OS: Android
 - Java Version: `17`
 - iCal4j Version: `3.2.12`

**Comment by odin568** [comment]
Issue not only happening with Wordpress Events Manager, also have a case with [eluceo/ical](https://packagist.org/packages/eluceo/ical)

Coming from https://github.com/bitfireAT/icsx5/discussions/198

**Comment by cbix** [comment]
I'm observing the same issue with iCal generated by the Wordpress [Event Calendar Plugin](https://wordpress.org/plugins/the-events-calendar/). Two calendar feeds using the `Europe/Berlin` timezone to validate:
- [Example 1](https://www.akut-theater99.de/events/liste/?ical=1)
- [Example 2](https://raststaette.org/termine/?ical=1)

**Comment by cbix** [comment]
Issue seems to be related to timezone definition.
This (for example) causes the issue:
```
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:20240331T010000
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:20241027T010000
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:20250330T010000
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:20251026T010000
END:STANDARD
END:VTIMEZONE
```
While this works as expected:
```
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
DTSTART:19810329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19961027T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
```

**Comment by benfortuna** [comment]
> Issue seems to be related to timezone definition. This (for example) causes the issue:
> 

If I'm not mistaken, that first example doesn't include any current timezone information as the DTSTART values are all in the future.

**Comment by cbix** [comment]
> the DTSTART values are all in the future

Good catch, I just reported this to the plugin's support forum. Seems like a few php-based generators use [`DateTimeZone::getTransitions($start, $end)`](https://www.php.net/manual/en/datetimezone.gettransitions.php) which gives you a fixed set of tz transitions as opposed to proper rrules.

What's still weird is that while all timezone DTSTARTs are in the future, it also causes later events within those intervals to be parsed with the wrong time.

**Comment by sunkup** [comment]
Another non working example. For this one the DTSTART values are not all in the future.

OS: Android
Java Version: 17.0.11
ical4j Version: 3.2.19

Expected behavior
After parsing the following calendar DTSTART should be 20240925T163000 and not 20230905T010000.

<details>

<summary>Calendar</summary>

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//wp-events-plugin.com//6.5.2//EN
TZID:Europe/Berlin
X-WR-TIMEZONE:Europe/Berlin
BEGIN:VEVENT
UID:xxx@xxx.de
DTSTART;TZID=Europe/Berlin:20240925T163000
DTEND;TZID=Europe/Berlin:20240925T180000
DTSTAMP:20240910T154945Z
SUMMARY:xxxx
DESCRIPTION:xxxx
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
DTSTART:20240331T030000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:20241027T020000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:20250330T030000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:20251026T020000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:20260329T030000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
END:DAYLIGHT
END:VTIMEZONE
END:VCALENDAR
```

</details>

@benfortuna When parsing using ical4j 4.0.4 the following exception is thrown. Is this expected behavior?

<details>

<summary>Exception</summary>

```
Error at line 35:End instant must be equal or after start instant
net.fortuna.ical4j.data.ParserException: Error at line 35:End instant must be equal or after start instant
	at app//net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:167)
	at app//net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:197)
	at app//net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:185)
	at app//at.bitfire.ical4android.validation.TimezoneIssues.test_parsing(Test.kt:82)
	at java.base@17.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.11/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base@17.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.11/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:119)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:66)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.time.DateTimeException: End instant must be equal or after start instant
	at org.threeten.extra.Interval.of(Interval.java:105)
	at net.fortuna.ical4j.model.Period.toInterval(Period.java:486)
	at net.fortuna.ical4j.model.Period.toInterval(Period.java:470)
	at net.fortuna.ical4j.model.Period.intersects(Period.java:464)
	at net.fortuna.ical4j.model.Component.calculateRecurrenceSet(Component.java:373)
	at net.fortuna.ical4j.model.ZoneRulesBuilder.buildDSTTransitions(ZoneRulesBuilder.java:86)
	at net.fortuna.ical4j.model.ZoneRulesBuilder.build(ZoneRulesBuilder.java:145)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.register(TimeZoneRegistryImpl.java:158)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.register(TimeZoneRegistryImpl.java:136)
	at net.fortuna.ical4j.data.DefaultContentHandler.endComponent(DefaultContentHandler.java:125)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:449)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:217)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:126)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:188)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:161)
	... 46 more
```  

Properties:
```
net.fortuna.ical4j.timezone.cache.impl=net.fortuna.ical4j.util.MapTimeZoneCache
net.fortuna.ical4j.timezone.offset.negative_dst_supported=true
net.fortuna.ical4j.timezone.registry=net.fortuna.ical4j.model.DefaultTimeZoneRegistryFactory
net.fortuna.ical4j.timezone.update.enabled=false
ical4j.unfolding.relaxed=true
ical4j.parsing.relaxed=true
ical4j.validation.relaxed=true
ical4j.compatibility.outlook=true
```

</details>
