### ISSUE TITLE
Unsupported component [VTIMEZONE]

### ISSUE THREAD

**Issue by jamieb22** [ical4j/ical4j#67]
Unsupported component VTIMEZONE when parsing events from the MS Exchange API. 

2015-12-30 08:38:01 c.s.a.ph [ERROR] failed to create calendar blob:Error at line 5:Unsupported component [VTIMEZONE]
net.fortuna.ical4j.data.ParserException: Error at line 5:Unsupported component [VTIMEZONE]
        at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:143) ~[ical4j-2.0-beta1.jar:na]
        at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:198) ~[ical4j-2.0-beta1.jar:na]
        at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:178) ~[ical4j-2.0-beta1.jar:na]
        at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:165) ~[ical4j-2.0-beta1.jar:na]
 ..
        at com.stimulus.util.f.run(MailArchiva:36) [f.class:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_66]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
Caused by: java.lang.IllegalArgumentException: Unsupported component [VTIMEZONE]
        at net.fortuna.ical4j.model.ComponentFactoryImpl.createComponent(ComponentFactoryImpl.java:84) ~[ical4j-2.0-beta1.jar:na]
        at net.fortuna.ical4j.data.CalendarBuilder$ContentHandlerImpl.startComponent(CalendarBuilder.java:317) ~[ical4j-2.0-beta1.jar:na]
        at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:379) ~[ical4j-2.0-beta1.jar:na]
        at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$900(CalendarParserImpl.java:367) ~[ical4j-2.0-beta1.jar:na]
        at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:171) ~[ical4j-2.0-beta1.jar:na]
        at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:122) ~[ical4j-2.0-beta1.jar:na]
        ... 24 common frames omitted

**Comment by benfortuna** [comment]
ical4j v2 now in maintenance mode only
