### ISSUE TITLE
extractor.ICalendarExtractor: Unable to parse icalendar with slashed

### ISSUE THREAD

**Issue by arsenyzb** [ical4j/ical4j#672]
**Describe the bug**

Cant parse such a vevent (seems like a slashes problem). Maybe there must be some document replace for slashes before parsing? But seems like it anyway better to fix in framework side. Thanks!

```
BEGIN:VCALENDAR
METHOD:REQUEST
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:France Standard Time
BEGIN:STANDARD
DTSTART:16010101T000000
TZOFFSETFROM:+0100
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T000000
TZOFFSETFROM:+0100
TZOFFSETTO:+0100
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ORGANIZER;CN=Juber:M
 AILTO:juber.selejie@mail.fr
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=Averk
 ali Sen Alinie:MAILTO:sen.alinie@mail.fr
DESCRIPTION;LANGUAGE=fr-FR:\n\n-----Original Appointment-----\nFrom: Jub
 er\; key-info@mail.fr\; Arutuan Edgar Coco
RRULE:FREQ=WEEKLY;INTERVAL=2;BYDAY=TU;WKST=MO
UID:111
SUMMARY;LANGUAGE=fr-FR:FW: Bone jour
DTSTART;TZID=France Standard Time:20230221T100000
DTEND;TZID=France Standard Time:20230221T103000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20230614T221830Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:16
LOCATION;LANGUAGE=fr-FR:frConf
X-MICROSOFT-CDO-APPT-SEQUENCE:16
X-MICROSOFT-CDO-OWNERAPPTID:-222
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
BEGIN:VALARM
DESCRIPTION:REMINDER
TRIGGER;RELATED=START:-PT15M
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR
```

Exception

```
net.fortuna.ical4j.data.ParserException: Error at line 24:Expected [61], read [59]
	at net.fortuna.ical4j.data.CalendarParserImpl.assertToken(CalendarParserImpl.java:467) ~[ical4j-4.0.0-beta9.jar:4.0.0-beta9]
	at net.fortuna.ical4j.data.CalendarParserImpl.access$700(CalendarParserImpl.java:55) ~[ical4j-4.0.0-beta9.jar:4.0.0-beta9]
	at net.fortuna.ical4j.data.CalendarParserImpl$ParameterParser.parse(CalendarParserImpl.java:340) ~[ical4j-4.0.0-beta9.jar:4.0.0-beta9]
	at net.fortuna.ical4j.data.CalendarParserImpl$ParameterParser.access$2000(CalendarParserImpl.java:318) ~[ical4j-4.0.0-beta9.jar:4.0.0-beta9]
	at net.fortuna.ical4j.data.CalendarParserImpl$ParameterListParser.parse(CalendarParserImpl.java:313) ~[ical4j-4.0.0-beta9.jar:4.0.0-beta9]
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(CalendarParserImpl.java:258) ~[ical4j-4.0.0-beta9.jar:4.0.0-beta9]
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.access$1100(CalendarParserImpl.java:234) ~[ical4j-4.0.0-beta9.jar:4.0.0-beta9]
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:219) ~[ical4j-4.0.0-beta9.jar:4.0.0-beta9]
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:427) ~[ical4j-4.0.0-beta9.jar:4.0.0-beta9]
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$900(CalendarParserImpl.java:404) ~[ical4j-4.0.0-beta9.jar:4.0.0-beta9]
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:217) ~[ical4j-4.0.0-beta9.jar:4.0.0-beta9]
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:126) ~[ical4j-4.0.0-beta9.jar:4.0.0-beta9]
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:188) ~[ical4j-4.0.0-beta9.jar:4.0.0-beta9]
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:161) ~[ical4j-4.0.0-beta9.jar:4.0.0-beta9]
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:197) ~[ical4j-4.0.0-beta9.jar:4.0.0-beta9]
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:185) ~[ical4j-4.0.0-beta9.jar:4.0.0-beta9]

```

**Comment by Crazyphil** [comment]
I can confirm this bug with a more recent example. It seems like ical4j isn't correctly treating escaped semicolons as part of the text and instead regards it as part of the iCal definition. The problem in my case is the ` \;` in the location title for the `X-APPLE-STRUCTURED-LOCATION`  tag. Interestingly, the library parses the `LOCATION` tag itself just fine.

**Exception**
```
net.fortuna.ical4j.data.ParserException: Error at line 39:Expected [61], read [59]
	at net.fortuna.ical4j.data.CalendarParserImpl.assertToken(r8-map-id-12786abe5df62f6a9e70afbd8d7893dc5e3a38e2be79699099ac9250609e6aa7:92)
	at net.fortuna.ical4j.data.CalendarParserImpl.-$$Nest$massertToken(r8-map-id-12786abe5df62f6a9e70afbd8d7893dc5e3a38e2be79699099ac9250609e6aa7:1)
	at net.fortuna.ical4j.data.CalendarParserImpl$ParameterParser.parse(r8-map-id-12786abe5df62f6a9e70afbd8d7893dc5e3a38e2be79699099ac9250609e6aa7:36)
	at net.fortuna.ical4j.data.CalendarParserImpl$ParameterParser.-$$Nest$mparse(r8-map-id-12786abe5df62f6a9e70afbd8d7893dc5e3a38e2be79699099ac9250609e6aa7:1)
	at net.fortuna.ical4j.data.CalendarParserImpl$ParameterListParser.parse(r8-map-id-12786abe5df62f6a9e70afbd8d7893dc5e3a38e2be79699099ac9250609e6aa7:17)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(r8-map-id-12786abe5df62f6a9e70afbd8d7893dc5e3a38e2be79699099ac9250609e6aa7:43)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.-$$Nest$mparse(r8-map-id-12786abe5df62f6a9e70afbd8d7893dc5e3a38e2be79699099ac9250609e6aa7:1)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(r8-map-id-12786abe5df62f6a9e70afbd8d7893dc5e3a38e2be79699099ac9250609e6aa7:47)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(r8-map-id-12786abe5df62f6a9e70afbd8d7893dc5e3a38e2be79699099ac9250609e6aa7:37)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.-$$Nest$mparse(r8-map-id-12786abe5df62f6a9e70afbd8d7893dc5e3a38e2be79699099ac9250609e6aa7:1)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(r8-map-id-12786abe5df62f6a9e70afbd8d7893dc5e3a38e2be79699099ac9250609e6aa7:33)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(r8-map-id-12786abe5df62f6a9e70afbd8d7893dc5e3a38e2be79699099ac9250609e6aa7:29)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(r8-map-id-12786abe5df62f6a9e70afbd8d7893dc5e3a38e2be79699099ac9250609e6aa7:15)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(r8-map-id-12786abe5df62f6a9e70afbd8d7893dc5e3a38e2be79699099ac9250609e6aa7:54)
	at net.fortuna.ical4j.data.CalendarBuilder.build(r8-map-id-12786abe5df62f6a9e70afbd8d7893dc5e3a38e2be79699099ac9250609e6aa7:14)
	at net.fortuna.ical4j.data.CalendarBuilder.build(r8-map-id-12786abe5df62f6a9e70afbd8d7893dc5e3a38e2be79699099ac9250609e6aa7:13)
	at at.bitfire.synctools.icalendar.ICalendarParser.parse(r8-map-id-12786abe5df62f6a9e70afbd8d7893dc5e3a38e2be79699099ac9250609e6aa7:43)
	... 44 more
```

**iCal file**
```ical
BEGIN:VCALENDAR
PRODID:-//Apple Inc.//iPhone OS 26.4.2//EN
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:Europe/Vienna
BEGIN:DAYLIGHT
DTSTART:19810329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19961027T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CLASS:PUBLIC
DESCRIPTION:Passwesen\nAntrag auf ID Austria
DTEND;TZID=Europe/Vienna:20260522T104000
DTSTAMP:20260522T062118Z
DTSTART;TZID=Europe/Vienna:20260522T103000
LAST-MODIFIED:20260522T062116Z
LOCATION:Hauptstraße 1-5\; 4041 Linz
SEQUENCE:0
SUMMARY:Antrag auf ID Austria
TRANSP:OPAQUE
UID:af64eb20-7d10-4482-8b22-921f7656390a
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-APPLE-MAPKIT-HANDLE=CAES1AEI2TIaEgn
 LfRdbrSdIQBHpqcQr/5AsQCJVCgdBdXN0cmlhEgJBVBoNVXBwZXIgQXVzdHJpYTIETGluejoEN
 DA0MEIGVXJmYWhyUgxIYXVwdHN0cmHDn2VaAzEtNWIQSGF1cHRzdHJhw59lIDEtNSoQSGF1cHR
 zdHJhw59lIDEtNTIQSGF1cHRzdHJhw59lIDEtNTIJNDA0MCBMaW56MgdBdXN0cmlhODlAAFABW
 iYKJBISCct9F1utJ0hAEempxCv/kCxAGNkyIO+4lcqkp+25AZADAQ==;X-APPLE-REFERENCEF
 RAME=1;X-TITLE=Hauptstraße 1-5\; 4041 Linz;X-APPLE-RADIUS=70.5873640261075
 6:geo:48.309978,14.283197
END:VEVENT
END:VCALENDAR
```

**Comment by benfortuna** [comment]
Initial assessment (using AI):

```
Root cause: X-TITLE=Hauptstraße 1-5\; 4041 Linz embeds an escaped semicolon
  inside a parameter value, which RFC 5545 forbids (parameter values use 
param-value/paramtext/quoted-string, none of which allow ; even escaped).
```

I'll see if there's a way we can allow it in relaxed mode.

**Comment by benfortuna** [comment]
fix applied will be in next release
