### ISSUE TITLE
`DateListPropertyRule` not fixing time zone name

### ISSUE THREAD

**Issue by ArnyminerZ** [ical4j/ical4j#678]
We are trying to use `DateListPropertyRule` to replace MS time zones to IANA. This was working on 3.2.14, but it doesn't work in 3.2.16.

To reproduce I've prepared this test:
```kotlin
class TestRules {
    @Test
    fun testApplyingRules() {
        javaClass.classLoader!!.getResourceAsStream("events/rules.ics").use { stream ->
            val reader = InputStreamReader(stream, Charsets.UTF_8)
            val calendar = CalendarBuilder().build(reader)
            val vEvent = calendar.getComponent(Component.VEVENT) as VEvent

            Assert.assertEquals("W. Europe Standard Time", vEvent.startDate.timeZone.id)
            val rule = DateListPropertyRule()
            for (component in calendar.components) {
                for (property in component.properties) {
                    if (!rule.supportedType.isAssignableFrom(property::class.java)) continue
                    (rule as Rfc5545PropertyRule<Property>).applyTo(property)
                }
            }
            Assert.assertEquals("Europe/Vienna", vEvent.startDate.timeZone.id)
        }
    }
}
```
and `rules.ics` is:
```ical
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
X-WR-CALNAME:Calendar
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
DESCRIPTION:\n.............................................................
 .................................\n\n\n
RRULE:FREQ=WEEKLY;UNTIL=20191218T080000Z;INTERVAL=1;BYDAY=WE;WKST=MO
UID:abc
SUMMARY:Weekly Meeting - Test
DTSTART;TZID=W. Europe Standard Time:20191023T090000
DTEND;TZID=W. Europe Standard Time:20191023T093000
END:VEVENT
END:VCALENDAR

```
It fails with:
```
org.junit.ComparisonFailure: expected:<[Europe/Vienna]> but was:<[W. Europe Standard Time]>
    at org.junit.Assert.assertEquals(Assert.java:117)
    at org.junit.Assert.assertEquals(Assert.java:146)
    at at.bitfire.ical4android.TestRules.testApplyingRules(TestRules.kt:29)
```

**Comment by benfortuna** [comment]
Apologies I made some changes to incorporate the MS timezones in the standard aliases that broke the rfc5545transformer. This has been fixed in 3.2.17.
