### ISSUE TITLE
Error at line 841:Invalid parameter name: FILENAME

### ISSUE THREAD

**Issue by alexolivas** [ical4j/ical4j#69]
I am trying to parse our client's google calendar, some of which have file attachment's in their events, but am getting the following exception when parsing the ics:

```
=75213399 2016-01-15 14:37:33,574 [task-scheduler-5] INFO  org.springframework.integration.mail.ImapMailReceiver  - attempting to receive mail from folder [INBOX]
=75214067 2016-01-15 14:37:34,242 [calendar-9] INFO  com.starfish.batch.integration.GoogleCalendarParser  - Using temp dir /var/log/starfish/starfish-batch-stage
=75214070 2016-01-15 14:37:34,245 [calendar-9] ERROR com.starfish.batch.integration.GoogleCalendarParser  - Exception getting user google cal for 4829on try number 2 trying again.
net.fortuna.ical4j.data.ParserException: Error at line 841:Invalid parameter name: FILENAME
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:148)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:211)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:192)
...
```

The ical that is produced when sharing the calendar and produces a parse exception is the following
```
BEGIN:VEVENT
DTSTART:20151210T143000Z
DTEND:20151210T183000Z
DTSTAMP:20160122T222759Z
UID:juu2r4kjaga6bk2u6cr98nc538@google.com
CREATED:20150909T112916Z
DESCRIPTION:Bring a side dish or salad.
LAST-MODIFIED:20151117T132256Z
LOCATION:
SEQUENCE:1
STATUS:CONFIRMED
SUMMARY:COED Holiday Celebration
TRANSP:OPAQUE
ATTACH;FILENAME=Reading Day Holiday Lunch 2015.docx:https://drive.google.com/a/uncc.edu/file/d/0BzcSudIsBZ3FWW9oaVFhTUV1bWc/view?usp=drive_web
END:VEVENT
```

However, if I change ATTACH;FILENAME to ATTACH;FMTTYPE the validation passes.

Are there plans to support this feature?

**Comment by arnaudq** [comment]
Answered your more basic question at http://stackoverflow.com/questions/34955725/error-parsing-google-icals-using-ical4j-library/34993214#34993214 but there is an ical4j extension repo at https://github.com/ical4j/ical4j-extensions for those. Feel free to send a patch.
