### ISSUE TITLE
module-info.java is incomplete in 4.0.0 and 4.0.1

### ISSUE THREAD

**Issue by mathisdt** [ical4j/ical4j#702]
**Describe the bug**
When including ical4j 4.0.0 (via Maven) in a project using the module system (in my case, SDB2 - see branch [ical4j-4.0.0](https://github.com/mathisdt/sdb2/tree/ical4j-4.0.0)), the project can be built but any tests using ical4j fail with the message:
```
ServiceConfiguration net.fortuna.ical4j.validate.CalendarValidatorFactory: module ical4j.core does not declare 'uses'
```
The same happens outside of tests in the application itself.

**To Reproduce**
1. include ical4j 4.0.0 in a project using the module system
2. call any ical4j function which uses a SPI

**Expected behavior**
No error is shown, but the function is executed.

**Environment**
 - OS: Linux
 - Java Version 21
 - iCal4j Version 4.0.0

**Additional context**
I would expect something like `uses net.fortuna.ical4j.validate.CalendarValidatorFactory;` (plus possibly some more lines like this for other used SPIs) in ical4j's `module-info.java` file.

**Comment by benfortuna** [comment]
Thanks for reporting this omission. I have added the required services in module-info. 

I still need to do some work such that I can run unit tests using module features, I think after that I should pick up these kind of errors more easily.

**Comment by mathisdt** [comment]
Nice, thanks for adding it! :+1: 

Not that I'm in a hurry, but when approximately is the next release planned? I noticed that you don't create releases in Github (which I could subscribe to) but only tags, so it would be nice to know...

**Comment by benfortuna** [comment]
Ah ok, yeah I use a gradle plugin to do the release. Not sure if there is one for github releases, but I'll check.

Generally I would like to release each month, but sometimes is longer (or shorter).

**Comment by mathisdt** [comment]
Thanks for releasing version 4.0.1! Sadly it still doesn't work for me, as the `uses` clauses are in place but the `provides` clauses are not. See e.g. [here](https://www.baeldung.com/java-modularity#7-provides--with) for more information about that.

**Comment by benfortuna** [comment]
Ah ok. So I've added the `provides` clauses now. If you like you can try the snapshot build to see if further changes are needed.

Snapshot versioning is a bit messed up right now, but if you refer to version [0.1.0-develop-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/mnode/ical4j/ical4j/0.1.0-develop-SNAPSHOT/) for the latest build.

**Comment by mathisdt** [comment]
Thanks! Now the JPMS part works, but I get the following error regarding the timezone "UTC". I think that's a different thing, so strictly speaking it doesn't belong here, but I include it as reference. Should I open another issue for that?

```
java.lang.RuntimeException: java.time.DateTimeException: Unknown timezone identifier [UTC]

	at org.zephyrsoft.sdb2/org.zephyrsoft.sdb2.util.calendar.ICalInterpreter.getInterpretedData(ICalInterpreter.java:126)
	at org.zephyrsoft.sdb2/org.zephyrsoft.sdb2.util.calendar.ICalInterpreterTest.wholeDayEvents(ICalInterpreterTest.java:49)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.time.DateTimeException: Unknown timezone identifier [UTC]
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.TimeZoneRegistryImpl.lambda$getZoneId$1(TimeZoneRegistryImpl.java:232)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.TimeZoneRegistryImpl.getZoneId(TimeZoneRegistryImpl.java:232)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.parameter.TzId.toZoneId(TzId.java:83)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.TemporalAdapter.getTemporal(TemporalAdapter.java:120)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.DateList.getDates(DateList.java:173)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.property.DateListProperty.getDates(DateListProperty.java:122)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.Component.lambda$calculateRecurrenceSet$5(Component.java:380)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.Component.calculateRecurrenceSet(Component.java:381)
	at org.zephyrsoft.sdb2/org.zephyrsoft.sdb2.util.calendar.ICalInterpreter.lambda$getInterpretedData$1(ICalInterpreter.java:94)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at org.zephyrsoft.sdb2/org.zephyrsoft.sdb2.util.calendar.ICalInterpreter.getInterpretedData(ICalInterpreter.java:103)
	... 4 more
```

**Comment by mathisdt** [comment]
:+1: Works with 4.0.2.
