### ISSUE TITLE
timezone UTC not recognized in 4.0.1

### ISSUE THREAD

**Issue by mathisdt** [ical4j/ical4j#705]
**Describe the bug**
When using [this file](https://raw.githubusercontent.com/mathisdt/sdb2/master/src/test/resources/multiple-days-event-without-time.ics) as input for ical4j 4.0.1 / 0.1.0-develop-SNAPSHOT, the following exception occurs:
```
java.lang.RuntimeException: java.time.DateTimeException: Unknown timezone identifier [UTC]

	at org.zephyrsoft.sdb2/org.zephyrsoft.sdb2.util.calendar.ICalInterpreter.getInterpretedData(ICalInterpreter.java:126)
	at org.zephyrsoft.sdb2/org.zephyrsoft.sdb2.util.calendar.ICalInterpreterTest.wholeDayEvents(ICalInterpreterTest.java:49)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.time.DateTimeException: Unknown timezone identifier [UTC]
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.TimeZoneRegistryImpl.lambda$getZoneId$1(TimeZoneRegistryImpl.java:232)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.TimeZoneRegistryImpl.getZoneId(TimeZoneRegistryImpl.java:232)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.parameter.TzId.toZoneId(TzId.java:83)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.TemporalAdapter.getTemporal(TemporalAdapter.java:120)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.DateList.getDates(DateList.java:173)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.property.DateListProperty.getDates(DateListProperty.java:122)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.Component.lambda$calculateRecurrenceSet$5(Component.java:380)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.Component.calculateRecurrenceSet(Component.java:381)
	at org.zephyrsoft.sdb2/org.zephyrsoft.sdb2.util.calendar.ICalInterpreter.lambda$getInterpretedData$1(ICalInterpreter.java:94)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at org.zephyrsoft.sdb2/org.zephyrsoft.sdb2.util.calendar.ICalInterpreter.getInterpretedData(ICalInterpreter.java:103)
	... 4 more
```

Reference: [This test](https://github.com/mathisdt/sdb2/blob/master/src/test/java/org/zephyrsoft/sdb2/util/calendar/ICalInterpreterTest.java#L33) is used above.

**To Reproduce**
1. Set up the situation as described above

**Expected behavior**
No exception occurs, but the test succeeds (as it did with the same input file with ical4j 3.2.18).

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: 21
 - iCal4j Version: 4.0.1 / 0.1.0-develop-SNAPSHOT

**Comment by benfortuna** [comment]
Hmm, so this format is actually not valid according to the spec: `EXDATE;TZID=UTC:20130628T160000Z`

```
      FORM #2: DATE WITH UTC TIME

      The date with UTC time, or absolute time, is identified by a LATIN
      CAPITAL LETTER Z suffix character, the UTC designator, appended to
      the time value.  For example, the following represents January 19,
      1998, at 0700 UTC:

       19980119T070000Z

      The "TZID" property parameter MUST NOT be applied to DATE-TIME
      properties whose time values are specified in UTC.
```

I think the correct thing for us to do here (for compatibility) is to remove the TZID parameter for any `FORM #2` dates. We already have some similar logic to remove TZID from `VTIMEZONE` definitions, so we might be able to do the same here.

I will have a look (but also if the source can be notified this is not a valid format that could be helpful).

**Comment by benfortuna** [comment]
FYI the latest snapshot build should have a fix for this if you want to test. Note that you need to enable the `RELAXED_PARSING` [compatibility hint](http://www.ical4j.org/compatibility/).

Will be included in the next release.

**Comment by mathisdt** [comment]
Thanks for following up on this! I have tried with the newest '0.1.0-develop-SNAPSHOT', now I get:

```
java.lang.RuntimeException: net.fortuna.ical4j.data.ParserException: Error at line 92:Unknown time-zone ID: ical4j~e971dd25-8060-4e66-82be-f001ee744668

	at org.zephyrsoft.sdb2/org.zephyrsoft.sdb2.util.calendar.ICalInterpreter.getInterpretedData(ICalInterpreter.java:126)
	at org.zephyrsoft.sdb2/org.zephyrsoft.sdb2.util.calendar.ICalInterpreterTest.wholeDayEvents(ICalInterpreterTest.java:49)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: net.fortuna.ical4j.data.ParserException: Error at line 92:Unknown time-zone ID: ical4j~e971dd25-8060-4e66-82be-f001ee744668
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:167)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:197)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:185)
	at org.zephyrsoft.sdb2/org.zephyrsoft.sdb2.util.calendar.ICalInterpreter.getInterpretedData(ICalInterpreter.java:86)
	... 4 more
Caused by: java.time.zone.ZoneRulesException: Unknown time-zone ID: ical4j~e971dd25-8060-4e66-82be-f001ee744668
	at java.base/java.time.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:281)
	at java.base/java.time.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:236)
	at java.base/java.time.ZoneRegion.ofId(ZoneRegion.java:121)
	at java.base/java.time.ZoneId.of(ZoneId.java:411)
	at java.base/java.time.ZoneId.of(ZoneId.java:359)
	at java.base/java.time.ZoneId.of(ZoneId.java:315)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.TimeZoneRegistryImpl.getZoneId(TimeZoneRegistryImpl.java:231)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.parameter.TzId.toZoneId(TzId.java:83)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.TemporalAdapter.getTemporal(TemporalAdapter.java:120)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.property.DateProperty.isUtc(DateProperty.java:295)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.PropertyBuilder.build(PropertyBuilder.java:116)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.data.DefaultContentHandler.endProperty(DefaultContentHandler.java:153)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(CalendarParserImpl.java:293)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:219)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:427)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:217)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:126)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:188)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:161)
	... 7 more
```

**Comment by benfortuna** [comment]
Ah, I forgot we can't really perform operations involving temporal values (i.e. `DateProperty.isUtc()`) until the build is complete. I have replaced the logic with another solution that should work for your specific example.

**Comment by mathisdt** [comment]
Thanks for wrapping your head around this! Sadly, the problem is still not gone (please see below for the stack trace).

You are welcome to directly check any changes, it would be as easy as this (given you have [JDK 21](https://adoptium.net/de/temurin/releases/?version=21&arch=x64) installed somewhere):
```
git clone --branch ical4j-4.0.0 https://github.com/mathisdt/sdb2.git
cd sdb2
JAVA_HOME=/your/path/to/jdk21 ./mvnw -Dtest=org.zephyrsoft.sdb2.util.calendar.ICalInterpreterTest test
```
The code on the branch is using ical4j `0.1.0-develop-SNAPSHOT`, so if you install it into your local repository, the test is possible without the roundtrip to Sonatype's repository.

----

Stack trace:
```
java.lang.RuntimeException: java.time.DateTimeException: Unknown timezone identifier [UTC]

	at org.zephyrsoft.sdb2/org.zephyrsoft.sdb2.util.calendar.ICalInterpreter.getInterpretedData(ICalInterpreter.java:126)
	at org.zephyrsoft.sdb2/org.zephyrsoft.sdb2.util.calendar.ICalInterpreterTest.wholeDayEvents(ICalInterpreterTest.java:49)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.time.DateTimeException: Unknown timezone identifier [UTC]
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.TimeZoneRegistryImpl.lambda$getZoneId$1(TimeZoneRegistryImpl.java:232)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.TimeZoneRegistryImpl.getZoneId(TimeZoneRegistryImpl.java:232)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.parameter.TzId.toZoneId(TzId.java:83)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.TemporalAdapter.getTemporal(TemporalAdapter.java:120)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.DateList.getDates(DateList.java:173)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.property.DateListProperty.getDates(DateListProperty.java:122)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.Component.lambda$calculateRecurrenceSet$5(Component.java:380)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at ical4j.core@0.1.0-develop-SNAPSHOT/net.fortuna.ical4j.model.Component.calculateRecurrenceSet(Component.java:381)
	at org.zephyrsoft.sdb2/org.zephyrsoft.sdb2.util.calendar.ICalInterpreter.lambda$getInterpretedData$1(ICalInterpreter.java:94)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at org.zephyrsoft.sdb2/org.zephyrsoft.sdb2.util.calendar.ICalInterpreter.getInterpretedData(ICalInterpreter.java:103)
	... 4 more
```

**Comment by benfortuna** [comment]
No probs, I actually ran one of the ical4j unit tests with your sample so was able to fix it properly in the latest snapshot.

Current solution is a bit simple, just removing `TZID=UTC` parameters, so may need to do some more work if it causes issues for others. For now I think will be ok.

**Comment by mathisdt** [comment]
Thank you! Now this seems to be sorted out. I ran into another problem regarding generics, but I will open another issue for that because it seems unrelated (#707).

**Comment by mathisdt** [comment]
:+1: Works in 4.0.2.
