### ISSUE TITLE
event.calculateRecurrenceSet() throwing IllegalArgumentException with ical 4.0.1

### ISSUE THREAD

**Issue by hazra-mms** [ical4j/ical4j#706]
**Describe the bug**
While trying to update from iCal v3 to v4 we see the tests are broken and we do find the rules are not working as expected.

**To Reproduce**
```kotlin   
 @Test
    fun `test counted schedule boundary calculation sasas`() {
        val ics = """
            BEGIN:VCALENDAR
            PRODID:Test
            VERSION:2.0
            DESCRIPTION:
            BEGIN:VEVENT
            DTSTAMP:20230627T162831Z
            DTSTART:20230626T220000Z
            RRULE:FREQ=MONTHLY;COUNT=4;INTERVAL=3;BYDAY=SU;BYHOUR=4;BYMINUTE=0;BYSECOND=0
            TZID:Europe/Brussels
            SUMMARY:
            UID:e413d780-14f6-11ee-b3ec-8db540d255bf
            END:VEVENT
            END:VCALENDAR""".trimIndent()

        val cal = CalendarBuilder().build(UnfoldingReader(StringReader(ics), true))
        val event = cal.getComponents<VEvent>().first()
        val period = Period(
            OffsetDateTime.now(),
            ChronoUnit.MILLENNIA.duration
        )
        val calculateRecurrenceSet = event.calculateRecurrenceSet(period)
        println(calculateRecurrenceSet)
    }
```

**Current behavior**

```
java.lang.IllegalArgumentException: Invalid temporal type for this rule

	at net.fortuna.ical4j.transform.recurrence.AbstractDateExpansionRule.getTemporalField(AbstractDateExpansionRule.java:135)
	at net.fortuna.ical4j.transform.recurrence.AbstractDateExpansionRule.getYear(AbstractDateExpansionRule.java:126)
	at net.fortuna.ical4j.transform.recurrence.ByMonthDayRule$ExpansionFilter.apply(ByMonthDayRule.java:79)
	at net.fortuna.ical4j.transform.recurrence.ByMonthDayRule.apply(ByMonthDayRule.java:55)
	at net.fortuna.ical4j.model.Recur.getCandidates(Recur.java:903)
	at net.fortuna.ical4j.model.Recur$DateSpliterator.tryAdvance(Recur.java:1302)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.fortuna.ical4j.model.Recur.getDates(Recur.java:764)
	at net.fortuna.ical4j.model.Recur.getDates(Recur.java:745)
	at net.fortuna.ical4j.model.Component.lambda$calculateRecurrenceSet$1(Component.java:357)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.fortuna.ical4j.model.Component.calculateRecurrenceSet(Component.java:359)
```

**Expected behavior**
calculated recurrence should be valid.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Mac
 - Java Version 21
 - iCal4j Version 4.0.1

**Additional context**

**Comment by benfortuna** [comment]
So I think this is due to the use of the new date/time API in v4, which is a bit less forgiving with temporal types. In this case you have a `DTSTART` in UTC time (DATE FORM 2), which is represented by `java.time.Instant`.

Instant does not support temporal fields such as day, month, year, etc. so calculating recurrences with the rule `RRULE:FREQ=MONTHLY;COUNT=4;INTERVAL=3;BYDAY=SU;BYHOUR=4;BYMINUTE=0;BYSECOND=0` will fail. 

You can confirm this by changing the DTSTART value to floating time (or with a specific TZID).

**Comment by seehausen** [comment]
Thanks for your answer. We checked it, and yes it would work if we would specify DTSTART as e.g. `DTSTART;TZID=America/New_York:20080807T090000`
BUT
that would mean that we need to migrate all existing ical entries in our database and update all DTSTART fields which is only possible with high effort and risk
Is there any possibility to upgrade to version 4.x without DB migration? or that `calculateRecurrenceSet ()` accepts values in different formats (mixed Instant and OffsetDateTime)?

**Comment by benfortuna** [comment]
So there was previously a discussion (#613) around using `ZonedDateTime` for UTC properties, which I think won't work, but maybe we didn't explore `OffsetDateTime`. I will have a think about how we might be able to support it.

**Comment by benfortuna** [comment]
Ok I have just committed a change to use `OffsetDateTime` for properties that support multiple date types (such as `DTSTART`, `DTEND`, etc.).

I also added a [test](https://github.com/ical4j/ical4j/blob/develop/src/test/groovy/net/fortuna/ical4j/model/component/VEventSpec.groovy#L105) similar to the one above to verify it works.

You can try the snapshot build (use `0.1.0-develop-SNAPSHOT` for that currently), or wait for next release to try it.

NOTE: Properties that are UTC-only (e.g. `DTSTAMP`, `LAST-MODIFIED`, etc.) will keep using `Instant` for now.

**Comment by hazra-mms** [comment]
Thanks for this, I used the snapshot and looks like those are okay, I see some other tests also failing but maybe for different reason. We would play around and let you know our status. Thanks for the support!

**Comment by seehausen** [comment]
@benfortuna Thanks a lot, our last failing tests I could fix, so with some additional date conversions in our code, all our tests are green now...

Looking forward to seeing your changes in the next release
Holger-

**Comment by hazra-mms** [comment]
Hi @benfortuna , With the latest release we are able to solve the issues. Thanks a lot for your support.
