### ISSUE TITLE
Generic type definiton seems to be ignored

### ISSUE THREAD

**Issue by mathisdt** [ical4j/ical4j#707]
**Describe the bug**
The method `TemporalAdapter.toLocalTime()` seems to return a `ZonedDateTime`, regardless if another type is required by the generics - the value is simply cast into `T` which can't be checked at runtime because of type erasure. See [this code part](https://github.com/ical4j/ical4j/blob/03da0cd3d2d361972c8df25fcc5c62dc6b6e50c9/src/main/java/net/fortuna/ical4j/model/property/DateListProperty.java#L122). Or did I use the API wrong? :thinking: 

```
java.lang.RuntimeException: java.lang.ClassCastException: class java.time.ZonedDateTime cannot be cast to class java.time.OffsetDateTime (java.time.ZonedDateTime and java.time.OffsetDateTime are in module java.base of loader 'bootstrap')
	at org.zephyrsoft.sdb2@2.1.0-SNAPSHOT/org.zephyrsoft.sdb2.util.calendar.ICalInterpreter.getInterpretedData(ICalInterpreter.java:126)
	at org.zephyrsoft.sdb2@2.1.0-SNAPSHOT/org.zephyrsoft.sdb2.util.calendar.ICalInterpreterTest.wholeDayEvents(ICalInterpreterTest.java:49)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ClassCastException: class java.time.ZonedDateTime cannot be cast to class java.time.OffsetDateTime (java.time.ZonedDateTime and java.time.OffsetDateTime are in module java.base of loader 'bootstrap')
	at org.zephyrsoft.sdb2@2.1.0-SNAPSHOT/org.zephyrsoft.sdb2.util.calendar.ICalInterpreter.convert(ICalInterpreter.java:140)
	at org.zephyrsoft.sdb2@2.1.0-SNAPSHOT/org.zephyrsoft.sdb2.util.calendar.ICalInterpreter.lambda$getInterpretedData$0(ICalInterpreter.java:97)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:3099)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at org.zephyrsoft.sdb2@2.1.0-SNAPSHOT/org.zephyrsoft.sdb2.util.calendar.ICalInterpreter.getInterpretedData(ICalInterpreter.java:103)
	... 4 more
```

**To Reproduce**
Execute [this test](https://github.com/mathisdt/sdb2/blob/master/src/test/java/org/zephyrsoft/sdb2/util/calendar/ICalInterpreterTest.java), e.g. via these commands (given [JDK 21](https://adoptium.net/de/temurin/releases/?version=21&arch=x64) is installed somewhere):
```
git clone --branch ical4j-4.0.0 https://github.com/mathisdt/sdb2.git
cd sdb2
JAVA_HOME=/your/path/to/jdk21 ./mvnw -Dtest=org.zephyrsoft.sdb2.util.calendar.ICalInterpreterTest test
```

**Expected behavior**
No exception occurs, but the test succeeds (as it did with the same input file with ical4j 3.2.18).

**Environment**
- OS: Linux
- Java Version: 21
- iCal4j Version: 4.0.1 / 0.1.0-develop-SNAPSHOT

**Comment by benfortuna** [comment]
The challenge we have moving to the new date/time API is we need to know what temporal types we are working with, which can be challenging when iterating a set of `VEVENT` objects that have a mix of `DTSTART` properties (i.e. some `VALUE=DATE`, some with `TZID`, etc.). So the kind of iteration in this test may need to be modified.

That said, the API was not quite correct in assuming the temporal type of the `Period` in `Component.calculateRecurrenceSet()` (and `Recur.getDates()`) would be the same type as the returned values.

I've made a change to decouple the period argument from the return type such that you can use `Period<OffsetDateTime>` for the iteration, but the returned set may contain `Period<LocalDate>`, `Period<ZonedDateTime>`, etc. depending on the type used in the `DTSTART` property.

**Comment by mathisdt** [comment]
In 4.0.2 this issue is not fixed, the API still does not adhere to the defined generics.

I implemented a [(hopefully temporary) precaution so the correct type is returned](https://github.com/mathisdt/sdb2/commit/96dc9ae82899e9f9ef1556b1259d2d73bab408df#diff-e62ac8e105a8145ded3856dcb6bf8371ebe165288ac8fc8b25893c367a6026f0R160), but I'd really like to remove that as soon as possible although it works for the moment.

**Comment by benfortuna** [comment]
So just to explain a bit further the signature change in 4.02, this is the current [calculateRecurrenceSet](https://github.com/ical4j/ical4j/blob/develop/src/main/java/net/fortuna/ical4j/model/Component.java#L307) signature:

```java
public final <T extends Temporal> Set<Period<T>> calculateRecurrenceSet(final Period<? extends Temporal> period) {
...
```

Note that the argument generics no longer match the return value, as we can't determine upfront what the return type will be as it depends on the nested properties (i.e. `DTSTART`).

So the [code](https://github.com/mathisdt/sdb2/blob/master/src/main/java/org/zephyrsoft/sdb2/util/calendar/ICalInterpreter.java#L101) you have assuming the return type is `OffsetDateTime` may need to change to something more generic:

```java
Set<Period<? extends Temporal>> list = component.calculateRecurrenceSet(period);
```

unless you can assume the return type based on the input data (e.g. if all input data has DTSTART with VALUE=DATE you can assume `LocalDate`, or VALUE=DATE-TIME and all in UTC time can assume `OffsetDateTime`, etc.

**Comment by mathisdt** [comment]
Thanks for the explanation, I use `Set<Period<Temporal>>` now (the type `Set<Period<? extends Temporal>>` doesn't harmonize with the return type of `calculateRecurrenceSet()`).

@benfortuna As far as I'm concerned, this is solved, so I'll close the issue.
