### ISSUE TITLE
NullPointerException in Configurator

### ISSUE THREAD

**Issue by raboof** [ical4j/ical4j#713]
**Describe the bug**

When I start my program that uses ical4j on the server where it is deployed, I see an exception in the logs:

```
Jul 29 13:04:05 server calendar-export-start[164362]: Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String)" because "net.fortuna.ical4j.util.Configurator.CONFIG" is null
Jul 29 13:04:05 server calendar-export-start[164362]:         at net.fortuna.ical4j.util.Configurator.getProperty(Configurator.java:77)
Jul 29 13:04:05 server calendar-export-start[164362]:         at net.fortuna.ical4j.util.TimeZones.getDefault(TimeZones.java:85)
Jul 29 13:04:05 server calendar-export-start[164362]:         at net.fortuna.ical4j.model.TemporalComparator.<init>(TemporalComparator.java:27)
Jul 29 13:04:05 server calendar-export-start[164362]:         at net.fortuna.ical4j.model.TemporalComparator.<clinit>(TemporalComparator.java:20)
Jul 29 13:04:05 server calendar-export-start[164362]:         ... 43 more
```

This does not happen on my development environment, and seems very strange: `CONFIG` is populated in the static initializer and never written to after that, and the static initializer should run before calling any static methods, so this almost seems like a JRE bug - which seems unlikely as well, though.

**To Reproduce**

I consistently see it on this server, but I have not yet found a way to reproduce it in isolation

**Environment (please complete the following information):**
 - OS: NixOS unstable as of b73c2221a46c13557b1b3be9c2070cc42cf01eb3
 - Java Version 21.0.3
 - iCal4j Version 4.0.2 (but I also saw it with a 4.0.0 release candidate)

**Comment by raboof** [comment]
Ah, looking closer it actually makes sense, as this code is triggered from the initialization of `Configurtor.LOG`, which is before the initialization of `Configurtor.CONFIG`. I'll look into this some more (though now I'm confused this doesn't happen during local development :) )

```
Jul 29 13:16:57 server calendar-export-start[165498]: Exception in thread "main" java.util.ServiceConfigurationError: java.time.zone.ZoneRulesProvider: Provider net.fortuna.ical4j.model.DefaultZoneRulesProvider could not be instantiated
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/java.time.zone.ZoneRulesProvider.<clinit>(ZoneRulesProvider.java:177)
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/java.time.ZoneRegion.ofId(ZoneRegion.java:121)
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/java.time.ZoneId.of(ZoneId.java:411)
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/java.time.ZoneId.of(ZoneId.java:359)
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/java.time.ZoneId.of(ZoneId.java:315)
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/java.util.TimeZone.toZoneId0(TimeZone.java:605)
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/java.util.TimeZone.toZoneId(TimeZone.java:582)
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/java.util.TimeZone.toZoneId0(TimeZone.java:594)
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/java.util.TimeZone.toZoneId(TimeZone.java:582)
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/java.time.ZoneId.systemDefault(ZoneId.java:275)
Jul 29 13:16:57 server calendar-export-start[165498]:         at ch.qos.logback.core.util.CachingDateFormatter.<init>(CachingDateFormatter.java:57)
Jul 29 13:16:57 server calendar-export-start[165498]:         at ch.qos.logback.core.util.CachingDateFormatter.<init>(CachingDateFormatter.java:52)
Jul 29 13:16:57 server calendar-export-start[165498]:         at ch.qos.logback.core.util.CachingDateFormatter.<init>(CachingDateFormatter.java:48)
Jul 29 13:16:57 server calendar-export-start[165498]:         at ch.qos.logback.classic.layout.TTLLLayout.<init>(TTLLLayout.java:40)
Jul 29 13:16:57 server calendar-export-start[165498]:         at ch.qos.logback.classic.BasicConfigurator.configure(BasicConfigurator.java:51)
Jul 29 13:16:57 server calendar-export-start[165498]:         at ch.qos.logback.classic.util.ContextInitializer.invokeConfigure(ContextInitializer.java:128)
Jul 29 13:16:57 server calendar-export-start[165498]:         at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:103)
Jul 29 13:16:57 server calendar-export-start[165498]:         at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:66)
Jul 29 13:16:57 server calendar-export-start[165498]:         at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:52)
Jul 29 13:16:57 server calendar-export-start[165498]:         at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
Jul 29 13:16:57 server calendar-export-start[165498]:         at org.slf4j.LoggerFactory.bind(LoggerFactory.java:196)
Jul 29 13:16:57 server calendar-export-start[165498]:         at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:183)
Jul 29 13:16:57 server calendar-export-start[165498]:         at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:486)
Jul 29 13:16:57 server calendar-export-start[165498]:         at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:472)
Jul 29 13:16:57 server calendar-export-start[165498]:         at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:421)
Jul 29 13:16:57 server calendar-export-start[165498]:         at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:447)
Jul 29 13:16:57 server calendar-export-start[165498]:         at net.fortuna.ical4j.util.Configurator.<clinit>(Configurator.java:54)
Jul 29 13:16:57 server calendar-export-start[165498]:         at KalenderAlgemeen$package$.kalenderAlgemeen(KalenderAlgemeen.scala:136)
Jul 29 13:16:57 server calendar-export-start[165498]:         at kalenderAlgemeen.main(KalenderAlgemeen.scala:134)
Jul 29 13:16:57 server calendar-export-start[165498]: Caused by: java.lang.ExceptionInInitializerError
Jul 29 13:16:57 server calendar-export-start[165498]:         at net.fortuna.ical4j.model.TemporalAdapter.<clinit>(TemporalAdapter.java:37)
Jul 29 13:16:57 server calendar-export-start[165498]:         at net.fortuna.ical4j.model.property.DateProperty.setDate(DateProperty.java:171)
Jul 29 13:16:57 server calendar-export-start[165498]:         at net.fortuna.ical4j.model.property.DtStart.<init>(DtStart.java:144)
Jul 29 13:16:57 server calendar-export-start[165498]:         at net.fortuna.ical4j.model.TimeZoneLoader.<clinit>(TimeZoneLoader.java:49)
Jul 29 13:16:57 server calendar-export-start[165498]:         at net.fortuna.ical4j.model.DefaultZoneRulesProvider.<init>(DefaultZoneRulesProvider.java:32)
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
Jul 29 13:16:57 server calendar-export-start[165498]:         at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
Jul 29 13:16:57 server calendar-export-start[165498]:         ... 31 more
Jul 29 13:16:57 server calendar-export-start[165498]: Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String)" because "net.fortuna.ical4j.util.Configurator.CONFIG" is null
Jul 29 13:16:57 server calendar-export-start[165498]:         at net.fortuna.ical4j.util.Configurator.getProperty(Configurator.java:77)
Jul 29 13:16:57 server calendar-export-start[165498]:         at net.fortuna.ical4j.util.TimeZones.getDefault(TimeZones.java:85)
Jul 29 13:16:57 server calendar-export-start[165498]:         at net.fortuna.ical4j.model.TemporalComparator.<init>(TemporalComparator.java:27)
Jul 29 13:16:57 server calendar-export-start[165498]:         at net.fortuna.ical4j.model.TemporalComparator.<clinit>(TemporalComparator.java:20)
Jul 29 13:16:57 server calendar-export-start[165498]:         ... 40 more
```

**Comment by benfortuna** [comment]
Keep it open for now, i will have  a closer look to see if I can make any improvements. Thanks for reporting.

**Comment by benfortuna** [comment]
I've made an adjustment to prevent the null pointer exception, by deferring log initialisation until after config is loaded
