### ISSUE TITLE
VAlarm cannot be cast to class CalendarComponent

### ISSUE THREAD

**Issue by MarcinJedrzejczyk94** [ical4j/ical4j#714]
**Describe the bug**

new CalendarBuilder().build() is throwing ParserException due to net.fortuna.ical4j.model.component.VAlarm cannot be cast to class net.fortuna.ical4j.model.component.CalendarComponent

```
Caused by: net.fortuna.ical4j.data.ParserException: Error at line 20:class net.fortuna.ical4j.model.component.VAlarm cannot be cast to class net.fortuna.ical4j.model.component.CalendarComponent (net.fortuna.ical4j.model.component.VAlarm and net.fortuna.ical4j.model.component.CalendarComponent are in unnamed module of loader 'app')
        at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:167)
        at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:197)
        at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:185)
        at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:172)
        at com.smartrecruiters.email.tracker.incomingemails.ICalReplyExtractor.parseICal(ICalReplyExtractor.java:84)
        ... 59 common frames omitted
Caused by: java.lang.ClassCastException: class net.fortuna.ical4j.model.component.VAlarm cannot be cast to class net.fortuna.ical4j.model.component.CalendarComponent (net.fortuna.ical4j.model.component.VAlarm and net.fortuna.ical4j.model.component.CalendarComponent are in unnamed module of loader 'app')
        at net.fortuna.ical4j.data.DefaultContentHandler.endComponent(DefaultContentHandler.java:121)
        at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:449)
        at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:217)
        at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:126)
        at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:188)
        at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:161)
        ... 63 common frames omitted
```

The usage in our code is 
```
        setHintEnabled(KEY_RELAXED_UNFOLDING, true);
        setHintEnabled(KEY_RELAXED_PARSING, true);
        setHintEnabled(KEY_RELAXED_VALIDATION, true);
        setHintEnabled(KEY_OUTLOOK_COMPATIBILITY, true);

        try {
            return new CalendarBuilder().build(new ByteArrayInputStream(data));
        } catch (IOException | ParserException e) {
            throw new CannotParseException(e);
        }
```

In 4.0.1 this code was not generating this exception.
I think it could be related to https://github.com/ical4j/ical4j/commit/6dc825851152371d252b76fc951f2ba9e1690eb6#diff-6b8fa9882b560c1a9c32a6e5b218e0fa0545c6840267a8aa3f1c543c2d1207baR196

**To Reproduce**
Steps to reproduce the behaviour:
1. Take the example text block
2. Use getBytes on the example data
3. Use new CalendarBuilder().build(new ByteArrayInputStream(data)) to create Calendar object

**Expected behavior**
No net.fortuna.ical4j.data.ParserException is being thrown when using ical4j new CalendarBuilder() to create Calendar object

**Environment (please complete the following information):**
 - Java Version 21

** Example data for issue reproduction**
```
            """
            BEGIN:VCALENDAR
            PRODID:-//Google Inc//Google Calendar 70.9054//EN
            VERSION:2.0
            CALSCALE:GREGORIAN
            METHOD:REPLY
            BEGIN:VEVENT
            UID:${uid}
            ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=${action};CN=Candidate
             Name;X-NUM-GUESTS=0:mailto:${conversationHash}@smartrecruiters.com
            SEQUENCE:0
            STATUS:CONFIRMED
            END:VEVENT
            BEGIN:VALARM
            TRIGGER:-PT30M
            REPEAT:2
            DURATION:PT15M
            ACTION:DISPLAY
            DESCRIPTION:Breakfast meeting with executive
            ACKNOWLEDGED:20130927T141516Z
            END:VALARM
            END:VCALENDAR
            """;
```

**Comment by benfortuna** [comment]
Hi, actually there is a problem with the data as the `VALARM` component must be nested inside the associated `VEVENT`, e.g:

```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REPLY
BEGIN:VEVENT
UID:${uid}
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=${action};CN=Candidate
 Name;X-NUM-GUESTS=0:mailto:${conversationHash}@smartrecruiters.com
SEQUENCE:0
STATUS:CONFIRMED
BEGIN:VALARM
TRIGGER:-PT30M
REPEAT:2
DURATION:PT15M
ACTION:DISPLAY
DESCRIPTION:Breakfast meeting with executive
ACKNOWLEDGED:20130927T141516Z
END:VALARM
END:VEVENT
END:VCALENDAR
```

I am not sure there is any benefit to making this more lenient unless there are examples where this usage of `VALARM` as a top-level component is supported..

**Comment by MarcinJedrzejczyk94** [comment]
alright, I updated the example data to 
```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REPLY
BEGIN:VEVENT
UID:${uid}
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=${action};CN=Candidate
 Name;X-NUM-GUESTS=0:mailto:${conversationHash}@smartrecruiters.com
SEQUENCE:0
STATUS:CONFIRMED
BEGIN:VALARM
TRIGGER:-PT30M
REPEAT:2
DURATION:PT15M
ACTION:DISPLAY
DESCRIPTION:Breakfast meeting with executive
ACKNOWLEDGED:20130927T141516Z
END:VALARM
END:VEVENT
END:VCALENDAR
```

And issue no longer occurs
