### ISSUE TITLE
net.fortuna.ical4j.data.ParserException for calendars with VTIMEZONEs elements

### ISSUE THREAD

**Issue by andrzej-talarek** [ical4j/ical4j#743]
**Describe the bug**
When trying to parse valid ical that contain multiple VTIMEZONE elements, net.fortuna.ical4j.data.ParserException is thrown with message `Error at line X:End instant must be equal or after start instant`
For attached test it is exactly:
```
End instant must be equal or after start instant
java.time.DateTimeException: End instant must be equal or after start instant
	at org.threeten.extra.Interval.of(Interval.java:105)
	at net.fortuna.ical4j.model.Period.toInterval(Period.java:486)
	at net.fortuna.ical4j.model.Period.toInterval(Period.java:470)
	at net.fortuna.ical4j.model.Period.intersects(Period.java:464)
	at net.fortuna.ical4j.model.Component.calculateRecurrenceSet(Component.java:373)
	at net.fortuna.ical4j.model.ZoneRulesBuilder.buildDSTTransitions(ZoneRulesBuilder.java:86)
	at net.fortuna.ical4j.model.ZoneRulesBuilder.build(ZoneRulesBuilder.java:145)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.register(TimeZoneRegistryImpl.java:158)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.register(TimeZoneRegistryImpl.java:136)
	at net.fortuna.ical4j.data.DefaultContentHandler.endComponent(DefaultContentHandler.java:125)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:449)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:217)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:126)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:188)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:161)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:197)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:185)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:172)
	at pl.waw.zks.IcalFailedTest.ical file should be loaded using ical4j(IcalFailedTest.kt:52)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**To Reproduce**
1. Use following test
```
import net.fortuna.ical4j.data.CalendarBuilder
import org.junit.jupiter.api.Test
import java.io.ByteArrayInputStream

class IcalFailedTest {
    @Test
    fun `ical file should be loaded using ical4j`() {
        val ics = """
            BEGIN:VCALENDAR
            VERSION:2.0
            CALSCALE:GREGORIAN
            METHOD:PUBLISH
            BEGIN:VTIMEZONE
            TZID:Europe/Warsaw
            BEGIN:DAYLIGHT
            TZOFFSETFROM:+0100
            TZOFFSETTO:+0200
            TZNAME:CEST
            DTSTART:20240331T010000
            END:DAYLIGHT
            BEGIN:STANDARD
            TZOFFSETFROM:+0200
            TZOFFSETTO:+0100
            TZNAME:CET
            DTSTART:20241027T010000
            END:STANDARD
            BEGIN:DAYLIGHT
            TZOFFSETFROM:+0100
            TZOFFSETTO:+0200
            TZNAME:CEST
            DTSTART:20250330T010000
            END:DAYLIGHT
            BEGIN:STANDARD
            TZOFFSETFROM:+0200
            TZOFFSETTO:+0100
            TZNAME:CET
            DTSTART:20251026T010000
            END:STANDARD
            END:VTIMEZONE
            END:VCALENDAR
        """.trimIndent()

        ByteArrayInputStream(ics.encodeToByteArray()).use { inputStream ->
            CalendarBuilder().build(inputStream)
        }
    }
}
```

**Expected behavior**
Since ical is valid, it should be parsed and loaded

**Environment (please complete the following information):**
 - OS: Linux (Fedora Linux 40)
 - Java Version: openjdk version "22.0.2" 2024-07-16
 - iCal4j Version: 4.0.04

**Comment by andrzej-talarek** [comment]
In case you don't use Kotlin, here is Java version:
```
import net.fortuna.ical4j.data.CalendarBuilder;
import net.fortuna.ical4j.data.ParserException;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

class IcalFailedTest {
  @Test
  void icalFileShouldBeLoadedUsingIcal4j() throws ParserException, IOException {
    var ics = """
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VTIMEZONE
TZID:Europe/Warsaw
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:20240331T010000
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:20241027T010000
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:20250330T010000
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:20251026T010000
END:STANDARD
END:VTIMEZONE
END:VCALENDAR""";

    new CalendarBuilder().build(new ByteArrayInputStream(ics.getBytes(StandardCharsets.UTF_8)));
  }
}
```
Exception thrown:
```
Error at line 31:End instant must be equal or after start instant
net.fortuna.ical4j.data.ParserException: Error at line 31:End instant must be equal or after start instant
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:167)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:197)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:185)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:172)
	at IcalFailedTest.icalFileShouldBeLoadedUsingIcal4j(IcalFailedTest.java:52)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.time.DateTimeException: End instant must be equal or after start instant
	at org.threeten.extra.Interval.of(Interval.java:105)
	at net.fortuna.ical4j.model.Period.toInterval(Period.java:486)
	at net.fortuna.ical4j.model.Period.toInterval(Period.java:470)
	at net.fortuna.ical4j.model.Period.intersects(Period.java:464)
	at net.fortuna.ical4j.model.Component.calculateRecurrenceSet(Component.java:373)
	at net.fortuna.ical4j.model.ZoneRulesBuilder.buildDSTTransitions(ZoneRulesBuilder.java:86)
	at net.fortuna.ical4j.model.ZoneRulesBuilder.build(ZoneRulesBuilder.java:145)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.register(TimeZoneRegistryImpl.java:158)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.register(TimeZoneRegistryImpl.java:136)
	at net.fortuna.ical4j.data.DefaultContentHandler.endComponent(DefaultContentHandler.java:125)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:449)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:217)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:126)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:188)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:161)
	... 7 more
```

**Comment by andrzej-talarek** [comment]
OK, now I know better what is the problem. Test can be simplified to single DST definition - problem is when definition starts in the future and doesn't have `RRULE` elements:
```
import net.fortuna.ical4j.data.CalendarBuilder;
import net.fortuna.ical4j.data.ParserException;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

class IcalFailedTest {
  @Test
  void icalFileShouldBeLoadedUsingIcal4j() throws ParserException, IOException {
    var ics = """
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VTIMEZONE
TZID:Europe/Warsaw
BEGIN:DAYLIGHT
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:20250330T020000
END:DAYLIGHT
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:20251026T030000
END:STANDARD
END:VTIMEZONE
END:VCALENDAR""";

    new CalendarBuilder().build(new ByteArrayInputStream(ics.getBytes(StandardCharsets.UTF_8)));
  }
}
```
Period sent to `calculateRecurrenceSet` is "negative", e.g. `20250330T020000/20240927T055617` and library is trying to create `org.threeten.extra.Interval` instance also being "negative".

**Comment by benfortuna** [comment]
Yeah I have recently added a fix for "future" timezone rules, which I think will fix this issue. Will be included in the next release.

**Comment by andrzej-talarek** [comment]
Thanks!
