### ISSUE TITLE
ClassCastException XComponent 

### ISSUE THREAD

**Issue by querdenker2k** [ical4j/ical4j#86]
Hi @benfortuna ,

I've got a new error now. Can you please have a look at this:

net.fortuna.ical4j.data.ParserException: Error at line 13:net.fortuna.ical4j.model.component.XComponent cannot be cast to net.fortuna.ical4j.model.component.Observance
        at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:143)
        at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:198)
...

Kind regards
 querdenker2k

**Comment by benfortuna** [comment]
Hi,

This appears to be a problem with locating the factories used in parsing. It is a known issue with Android, and I am looking into the best way to fix this. Can you confirm your environment and version you are using? Thanks.

**Comment by querdenker2k** [comment]
I am using the version from here: https://github.com/ical4j/ical4j/issues/64#issuecomment-215686118
Environment is openHAB on Java8 Ubuntu x64.
