### ISSUE TITLE
Throwing NumberFormatException

### ISSUE THREAD

**Issue by vsachinv** [ical4j/ical4j#88]
With Following Recurrence pattern throwing NumberFormatException.
"FREQ=WEEKLY;BYDAY=;INTERVAL=1"

Exception:

java.lang.NumberFormatException: For input string: "INTERV"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.parseInt(Integer.java:527)
	at net.fortuna.ical4j.util.Numbers.parseInt(Numbers.java:60)
	at net.fortuna.ical4j.model.WeekDay.<init>(WeekDay.java:100)
	at net.fortuna.ical4j.model.WeekDayList.<init>(WeekDayList.java:80)
	at net.fortuna.ical4j.model.Recur.<init>(Recur.java:232)
	at net.fortuna.ical4j.model.property.RRule.setValue(RRule.java:113)
	at net.fortuna.ical4j.model.property.RRule.<init>(RRule.java:70)

**Comment by fatkudu** [comment]
Probably not the best error reporting but I guess it is the empty BYDAY value that is the root issue.
The value needs to be one or more from "SU" / "MO" / "TU" / "WE" / "TH" / "FR" / "SA"
separated by commas.  See http://tools.ietf.org/html/rfc5545#section-3.3.10

**Comment by vsachinv** [comment]
Sorry! for reporting like this. But I wanted to check isn't there any default handling if BYDAY is empty ? and can we have more appropriate Validation Exception rather than this NumberFormatException?

**Comment by fatkudu** [comment]
By my reading of the RFC an empty value is invalid.  I agree that the exception thrown isn't ideal.

**Comment by benfortuna** [comment]
I've updated parsing to handle empty recurrence rule parts, #89 - will be included in the next release.

regards,
ben

**Comment by vsachinv** [comment]
Thanks! @benfortuna for adding the fix for the issue :)
